// Generated by scripts/build-patterns.ts from the spec (0.3.0). Do not edit.
import type { Rule } from "@polyxd/spec/patterns";

/** Each spec pattern's checks, by pattern id. */
export const PATTERN_CHECKS: Record<string, Rule[]> = {
 "compare-and-choose": [
  {
   "id": "one-comparison",
   "description": "Exactly one Comparison",
   "severity": "error",
   "rule": {
    "check": "contains",
    "component": "Comparison",
    "min": 1,
    "max": 1
   }
  },
  {
   "id": "can-choose",
   "description": "Each option can be chosen",
   "severity": "error",
   "rule": {
    "check": "requires",
    "component": "Comparison",
    "props": [
     "choose"
    ]
   }
  },
  {
   "id": "explains",
   "description": "A one-line summary or the recommendation's reason helps the decision",
   "severity": "warning",
   "rule": {
    "check": "anyOf",
    "checks": [
     {
      "check": "requires",
      "component": "Comparison",
      "props": [
       "summary"
      ]
     },
     {
      "check": "requires",
      "component": "Comparison",
      "props": [
       "recommendedReason"
      ]
     }
    ]
   }
  }
 ],
 "confirm-destructive": [
  {
   "id": "root-is-confirm",
   "description": "The surface is a confirmation dialog",
   "severity": "error",
   "rule": {
    "check": "rootIs",
    "components": [
     "Confirm"
    ]
   }
  },
  {
   "id": "states-consequence",
   "description": "It says what will happen and whether it can be undone",
   "severity": "error",
   "rule": {
    "check": "requires",
    "component": "Confirm",
    "props": [
     "consequence"
    ]
   }
  },
  {
   "id": "specific-confirm-label",
   "description": "The confirm button says what it does, never just 'OK' or 'Yes'",
   "severity": "error",
   "rule": {
    "check": "noLabelMatches",
    "pattern": "^(OK|Ok|Yes|Confirm|Submit|Done)$"
   }
  },
  {
   "id": "typed-for-destructive",
   "description": "Irreversible, high-impact deletions ask the user to type a confirmation",
   "severity": "warning",
   "rule": {
    "check": "requires",
    "component": "Confirm",
    "where": {
     "severity": "destructive"
    },
    "props": [
     "typeToConfirm"
    ]
   }
  }
 ],
 "filter-and-browse": [
  {
   "id": "has-results",
   "description": "Results are shown as a Collection or Table",
   "severity": "error",
   "rule": {
    "check": "anyOf",
    "checks": [
     {
      "check": "contains",
      "component": "Collection"
     },
     {
      "check": "contains",
      "component": "Table"
     }
    ]
   }
  },
  {
   "id": "filters-first",
   "description": "Filters come before the results",
   "severity": "error",
   "rule": {
    "check": "precedes",
    "before": [
     "TextInput",
     "Choice",
     "RangeInput",
     "DateInput"
    ],
    "after": [
     "Collection",
     "Table"
    ]
   }
  },
  {
   "id": "empty-state",
   "description": "Empty results explain what to do",
   "severity": "error",
   "rule": {
    "check": "allOf",
    "checks": [
     {
      "check": "requires",
      "component": "Collection",
      "props": [
       "empty"
      ]
     },
     {
      "check": "requires",
      "component": "Table",
      "props": [
       "empty"
      ]
     }
    ]
   }
  }
 ],
 "multi-step-form": [
  {
   "id": "form-or-steps",
   "description": "Inputs are collected in a Form or in Steps",
   "severity": "error",
   "rule": {
    "check": "anyOf",
    "checks": [
     {
      "check": "contains",
      "component": "Form"
     },
     {
      "check": "contains",
      "component": "Steps"
     }
    ]
   }
  },
  {
   "id": "short-views",
   "description": "No more than 6 inputs are visible at once; longer tasks are split into steps",
   "severity": "error",
   "rule": {
    "check": "maxInputsPerView",
    "max": 6
   }
  },
  {
   "id": "specific-submit",
   "description": "The submit button says what happens next",
   "severity": "warning",
   "rule": {
    "check": "noLabelMatches",
    "pattern": "^(OK|Ok|Yes|Confirm|Submit|Done)$"
   }
  }
 ],
 "review-and-submit": [
  {
   "id": "has-summary",
   "description": "What will be submitted is shown as label/value pairs",
   "severity": "error",
   "rule": {
    "check": "contains",
    "component": "DetailList"
   }
  },
  {
   "id": "submits",
   "description": "There is a way to submit",
   "severity": "error",
   "rule": {
    "check": "anyOf",
    "checks": [
     {
      "check": "contains",
      "component": "Form"
     },
     {
      "check": "contains",
      "component": "Steps"
     }
    ]
   }
  },
  {
   "id": "summary-before-inputs",
   "description": "Review content comes before any last inputs",
   "severity": "warning",
   "rule": {
    "check": "anyOf",
    "checks": [
     {
      "check": "not",
      "checks": [
       {
        "check": "contains",
        "component": "Toggle"
       }
      ]
     },
     {
      "check": "precedes",
      "before": [
       "DetailList"
      ],
      "after": [
       "Toggle"
      ]
     }
    ]
   }
  },
  {
   "id": "commitment-label",
   "description": "The submit label states the commitment, not 'Submit'",
   "severity": "error",
   "rule": {
    "check": "noLabelMatches",
    "pattern": "^(OK|Ok|Yes|Confirm|Submit|Done|Continue)$"
   }
  }
 ],
 "undo-over-confirm": [
  {
   "id": "has-undo-status",
   "description": "An undo notice says what happened",
   "severity": "error",
   "rule": {
    "check": "contains",
    "component": "Status",
    "where": {
     "kind": "undo"
    },
    "min": 1
   }
  },
  {
   "id": "undo-has-action",
   "description": "The notice offers Undo",
   "severity": "error",
   "rule": {
    "check": "requires",
    "component": "Status",
    "where": {
     "kind": "undo"
    },
    "props": [
     "action"
    ]
   }
  },
  {
   "id": "no-confirm",
   "description": "Nothing asks for confirmation first",
   "severity": "warning",
   "rule": {
    "check": "not",
    "checks": [
     {
      "check": "contains",
      "component": "Confirm"
     }
    ]
   }
  }
 ]
};
