/**
 * Builds the browser bundle `polyxd dev` renders with: the renderer, React, the validator that runs
 * in browsers, and every built-in theme, as one script and one stylesheet that need no bundler on
 * the other side.
 *
 *   preview/polyxd.js    window.Polyxd = { mount, validateDocument, themes, specVersion, … }
 *   preview/polyxd.css   the renderer's styles and all themes
 *
 * The script also honours the verifier harness's protocol: with `window.__PXD__ = { document,
 * theme, mode }` set before it loads, it renders into `#root` and records actions on
 * `window.__pxdActions`, so a page written for the harness renders with this bundle unchanged.
 *
 *   node scripts/build-preview.ts
 */
import { build } from "esbuild";
import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const themes = (await readdir(here("../themes"))).filter((f) => f.endsWith(".css")).map((f) => f.replace(/\.css$/, "")).sort();

const entry = `
import * as React from "react";
import { createRoot } from "react-dom/client";
import { PolyxdSurface, PolyxdSkeleton, getPointer, setPointer } from "../src/index.ts";
import { validateDocument, SPEC_VERSION, flattenTree, isTree } from "@polyxd/spec/browser";
import "../src/styles.css";
${themes.map((t) => `import "../themes/${t}.css";`).join("\n")}

const themes = ${JSON.stringify(themes)};

/** A grey square carrying the reference as its title: generated UIs never contain URLs. */
const placeholderMedia = (ref) => "data:image/svg+xml;utf8," + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><rect width="10" height="10" fill="#999"/><title>' + String(ref).replace(/[<&]/g, "") + '</title></svg>');

/**
 * Renders a document into an element and returns a handle to re-render it with new props or take
 * it down. Same-document updates keep the surface's state (what someone typed); a new \`key\` remounts.
 */
function mount(el, props) {
  const root = createRoot(el);
  const render = (p) => root.render(React.createElement(PolyxdSurface, { resolveMedia: placeholderMedia, ...p, key: p.key }));
  render(props);
  return { update: render, unmount: () => root.unmount() };
}

const api = { React, createRoot, PolyxdSurface, PolyxdSkeleton, getPointer, setPointer, validateDocument, flattenTree, isTree, mount, themes, specVersion: SPEC_VERSION, placeholderMedia };

if (typeof window !== "undefined") {
  window.Polyxd = api;
  // The verifier harness's protocol, so a harness page renders with this bundle unchanged.
  if (window.__PXD__ && document.getElementById("root")) {
    window.__pxdActions = [];
    window.__pxdDismissed = 0;
    const { document: doc, theme, mode } = window.__PXD__;
    mount(document.getElementById("root"), { document: doc, theme, mode, onAction: (e) => window.__pxdActions.push(e), onDismiss: () => (window.__pxdDismissed += 1) });
    requestAnimationFrame(() => requestAnimationFrame(() => (window.__pxdReady = true)));
  }
}
export default api;
`;

const result = await build({
  stdin: { contents: entry, resolveDir: here("."), loader: "tsx", sourcefile: "preview-entry.tsx" },
  bundle: true,
  // The spec's source rather than its dist, so this build never waits on a stale `tsc -b` there.
  alias: { "@polyxd/spec/browser": here("../../spec/src/browser.ts") },
  format: "iife",
  globalName: "PolyxdPreview",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  legalComments: "none",
  jsx: "automatic",
  define: { "process.env.NODE_ENV": '"production"' },
  outfile: here("../preview/polyxd.js"),
  logLevel: "warning",
  metafile: true,
});

const size = async (p: string) => `${Math.round((await stat(p)).size / 1024)} KB`;
const css = await readFile(here("../preview/polyxd.css"), "utf8");
// esbuild's CSS output keeps each theme's leading comment; one header is enough.
await writeFile(here("../preview/polyxd.css"), `/* @polyxd/react preview: renderer styles and the ${themes.join(", ")} themes. Generated by scripts/build-preview.ts. */\n` + css.replace(/\/\*[^*]*\*\/\s*/g, ""));
console.log(`wrote preview/polyxd.js (${await size(here("../preview/polyxd.js"))}) and preview/polyxd.css (${await size(here("../preview/polyxd.css"))}) with ${themes.length} themes`);
if (result.warnings.length) console.log(`${result.warnings.length} warning(s)`);
