/**
 * Writes film-b4-return-the-shoes/index.html (and copies its assets) from
 * shared/film-b4-timings.json. The story is STORY-B4.md; the film is shared/film-b4.js.
 *
 *   node apps/film/hyperframes/music-b4.mjs   (the score, once)
 *   node apps/film/hyperframes/make-b4.mjs
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { SHOTS } from "./montage.mjs";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const DIR = here("film-b4-return-the-shoes");
const T = JSON.parse(readFileSync(here("shared/film-b4-timings.json"), "utf8"));
delete T._;

const COPY = [
  ["../../../packages/web/preview/polyxd-web.js", "polyxd/polyxd-web.js"],
  ["../../../packages/web/preview/polyxd-web.css", "polyxd/polyxd-web.css"],
  ["shared/mark.js", "shared/mark.js"],
  ["shared/kit.js", "shared/kit.js"],
  ["shared/kit.css", "shared/kit.css"],
  ["shared/film-b.css", "shared/film-b.css"],
  ["shared/morph.js", "shared/morph.js"],
  ["shared/hw-kit.js", "shared/hw-kit.js"],
  ["shared/film-b4.js", "shared/film-b4.js"],
  ["shared/film-b4.css", "shared/film-b4.css"],
  ["shared/sting-b.html", "shared/sting-b.html"],
  ["shared/outro-b.html", "shared/outro-b.html"],
  ["../assets/fonts/YoungSerif-Regular.ttf", "fonts/YoungSerif-Regular.ttf"],
  ["../assets/fonts/DMMono-Regular.ttf", "fonts/DMMono-Regular.ttf"],
  ["../assets/fonts/HankenGrotesk-latin.woff2", "fonts/HankenGrotesk-latin.woff2"],
];
for (const [from, to] of COPY) {
  const dest = `${DIR}/assets/${to}`;
  mkdirSync(dest.slice(0, dest.lastIndexOf("/")), { recursive: true });
  copyFileSync(here(from), dest);
}
// The montage: B1–B3's list, with the order-status screen (grey photo placeholders) swapped for the
// spec's task list.
const spec = (p) => JSON.parse(readFileSync(here(`../../../packages/spec/examples/${p}.json`), "utf8"));
const shots = SHOTS.map((s) => (s.name === "Order #4821" ? { frame: "phone", theme: "fluent", name: "Today", doc: () => spec("tasks-list") } : s)).slice(0, T.shots);
writeFileSync(`${DIR}/assets/montage.js`, `/* Generated by make-b4.mjs from montage.mjs. */\nwindow.MONTAGE = ${JSON.stringify(shots.map(({ doc, ...s }) => ({ ...s, doc: doc() })))};\n`);

// Sound design: HeyGen audio catalogue effects, resolved through media-use (see .media/manifest.jsonl).
const SFX = {
  whoosh: [".media/audio/sfx/sfx_001.mp3", 0.22, 1.06], // Quick Whoosh (00caa739)
  hit: [".media/audio/sfx/sfx_002.mp3", 0.42, 3.06], // Cinematic Sub Bass Hit (128d8419)
  tap: [".media/audio/sfx/sfx_003.mp3", 0.04, 0.26], // Soft muted tap (19bd1766)
  crumple: [".media/audio/sfx/sfx_004.mp3", 0.38, 1.2], // Paper crumple (25bf9c03)
  pop: [".media/audio/sfx/sfx_005.mp3", 0.02, 0.58], // UI Pop (4558aa13)
  swish: [".media/audio/sfx/sfx_006.mp3", 0.08, 0.26], // Fast whoosh (72d0b143)
  sparkle: [".media/audio/sfx/sfx_007.mp3", 0.68, 3.33], // Ascending chime sparkle (7a885578)
  paper: [".media/audio/sfx/sfx_008.mp3", 0.5, 1.01], // Page turn (9b77ef76)
  airy: [".media/audio/sfx/sfx_009.mp3", 0.6, 1.44], // Fast airy whoosh (a4855a82)
  typing: [".media/audio/sfx/sfx_010.mp3", 0.04, 2.33], // Keyboard Typing (e401e115)
  click: [".media/audio/sfx/sfx_011.mp3", 0.04, 0.19], // Sharp click (e7945ed1)
  chime: [".media/audio/sfx/sfx_012.mp3", 0.22, 1.34], // Bright electronic chime (ef870618)
  riser: [".media/audio/sfx/sfx_013.mp3", 2.08, 2.78], // Deep whoosh riser (f6995a68)
};
const cue = (k, at, vol) => ({ k, start: +Math.max(0, at - SFX[k][1]).toFixed(3), vol });
const cues = [
  cue("whoosh", 0.62, 0.3),
  cue("swish", T.askIn - 0.1, 0.25),
  cue("typing", T.typeFrom, 0.28),
  cue("tap", T.send, 0.5),
  cue("paper", T.circleOn + 0.3, 0.18),
  cue("click", T.count1, 0.3),
  cue("click", T.count2, 0.3),
  cue("click", T.count3, 0.34),
  cue("paper", T.arrowOn + 0.3, 0.16),
  cue("paper", T.strike + 0.2, 0.42),
  cue("crumple", T.crumple + 0.2, 0.45),
  cue("airy", T.crumple + 0.55, 0.32),
  cue("riser", T.hit, 0.45),
  cue("hit", T.hit, 0.34),
  ...[0, 1, 2, 3].map((i) => cue("pop", T.parts + i * T.partsEvery, 0.2)),
  cue("swish", T.punch + 0.2, 0.28),
  cue("paper", T.knewOn + 0.3, 0.16),
  cue("sparkle", T.sparkle, 0.22),
  cue("swish", T.pullback + 0.2, 0.2),
  cue("tap", T.tap + 0.2, 0.45),
  cue("chime", T.toast, 0.32),
  cue("whoosh", T.whip1 + 0.31, 0.34),
  cue("paper", T.arrowApp + 0.4, 0.16),
  cue("sparkle", T.tok1 + 0.2, 0.13),
  cue("paper", T.label1Strike + 0.1, 0.2),
  cue("sparkle", T.tok2 + 0.2, 0.13),
  cue("paper", T.label2Strike + 0.1, 0.2),
  cue("whoosh", T.whip2 + 0.31, 0.34),
  cue("swish", T.pushForm + 0.2, 0.22),
  ...[0, 1, 2, 3, 4].map((i) => cue("click", T.scanFrom + 0.22 + i * 0.36, 0.26)),
  cue("chime", T.markChecked + 0.2, 0.28),
  cue("hit", T.montage, 0.2),
  ...Array.from({ length: T.shots - 1 }, (_, i) => cue("tap", T.montage + (i + 1) * T.shot, 0.16)),
  cue("airy", T.montEnd + 0.3, 0.25),
].sort((a, b) => a.start - b.start);
const audio = cues
  .map((c, i) => `      <audio id="b4-sfx-${i}" src="${SFX[c.k][0]}" data-start="${c.start}" data-duration="${SFX[c.k][2]}" data-track-index="${12 + i}" data-volume="${c.vol}" data-audio-group="sfx"></audio>`)
  .join("\n");
const attr = (o) => JSON.stringify(o).replace(/"/g, "&quot;");
// The score: under everything. A low-pass closes over the turn (the paragraph balls up and the
// music goes under water) and opens on the reveal's hit; the level builds into the montage and dips
// a touch under the sting's and the outro's hits.
const musicChain = { version: 1, nodes: [{ type: "lowpass", id: "n1", label: "Turn filter", params: { frequency: 18000, q: 0.707, poles: "2" } }] };
const musicAuto = {
  version: 1,
  lanes: [
    { target: "fx.n1.frequency", points: [{ t: 0, v: 18000 }, { t: T.crumple, v: 18000 }, { t: T.crumple + 0.9, v: 900, curve: -0.4 }, { t: T.hit - 0.4, v: 1400 }, { t: T.hit, v: 18000 }] },
    { target: "volume", points: [{ t: 0, v: 0.9 }, { t: 0.45, v: 0.9 }, { t: 0.62, v: 0.72 }, { t: 1.6, v: 0.9 }, { t: T.pushForm, v: 0.9 }, { t: T.montage, v: 1 }, { t: T.final - 0.2, v: 1 }, { t: T.final, v: 0.8 }, { t: T.final + 1.2, v: 1 }] },
  ],
};
const bus = (id, label, vol, limit) => `      <hf-audio-group id="${id}" data-label="${label}" data-volume="${vol}" data-fx-chain="${attr({ version: 1, nodes: [{ type: "highpass", id: "n1", label: "Remove Rumble", params: { frequency: 30, q: 0.707, poles: "2" } }, ...(limit === undefined ? [] : [{ type: "limiter", id: "n2", label: "Ceiling", params: { limit, attack: 5, release: 80, level_out: 0 } }])] })}"></hf-audio-group>`;

const cap = (id, text, cls = "", style = "") =>
  `      <div id="${id}" class="b4cap ${cls}" style="${style}"><div class="mask" data-layout-allow-overflow><p class="line">${text
    .split(" ")
    .map((w) => `<span class="w">${w}</span>`)
    .join(" ")}</p></div></div>`;

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>Polyxd · B4 · Can I return these shoes?</title>
    <!-- Generated by apps/film/hyperframes/make-b4.mjs from shared/film-b4-timings.json. The story: STORY-B4.md. -->
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <link rel="stylesheet" href="assets/polyxd/polyxd-web.css" />
    <link rel="stylesheet" href="assets/shared/kit.css" />
    <link rel="stylesheet" href="assets/shared/film-b.css" />
    <link rel="stylesheet" href="assets/shared/film-b4.css" />
    <style>
      @font-face { font-family: "Young Serif"; src: url("assets/fonts/YoungSerif-Regular.ttf") format("truetype"); font-weight: 400; font-style: normal; }
      @font-face { font-family: "Hanken Grotesk"; src: url("assets/fonts/HankenGrotesk-latin.woff2") format("woff2"); font-weight: 100 900; font-style: normal; }
      @font-face { font-family: "DM Mono"; src: url("assets/fonts/DMMono-Regular.ttf") format("truetype"); font-weight: 400; font-style: normal; }
      @font-face { font-family: "Caveat"; src: url("assets/fonts/Caveat-700-latin.woff2") format("woff2"); font-weight: 700; font-style: normal; font-display: block; }
      @font-face { font-family: "SFMono-Regular"; src: local("SFMono-Regular"), local("SF Mono"); }
    </style>
    <script src="assets/polyxd/polyxd-web.js"></script>
    <script src="assets/shared/mark.js"></script>
    <script src="assets/shared/kit.js"></script>
    <script src="assets/shared/morph.js"></script>
    <script src="assets/shared/hw-kit.js"></script>
    <script src="assets/montage.js"></script>
    <script src="assets/shared/film-b4.js"></script>
  </head>
  <body>
    <svg width="0" height="0" style="position:absolute" aria-hidden="true"><filter id="b4-whip" x="-10%" y="0" width="120%" height="100%"><feGaussianBlur id="b4-whip-blur" stdDeviation="0 0" /></filter></svg>
    <div id="root" data-composition-id="film-b4" data-start="0" data-width="1920" data-height="1080" data-duration="${T.end}">
      <div id="b4-sting" data-composition-id="sting-b" data-composition-src="assets/shared/sting-b.html" data-start="0" data-duration="${T.stingDur}" data-track-index="1"></div>

      <div id="stagebox" class="group" style="opacity:0">
        <div id="persp">
          <div id="rig">
            <div class="phone"><div class="phone-glass"><div class="phone-screen" id="screen"></div></div></div>
            <div class="seat" id="seat"></div>
            <div id="ink"></div>
          </div>
        </div>
      </div>

      <div id="turn"><div id="turn-mark"></div></div>

      <div id="mont" class="group">
        <div class="phone" id="m-phone"><div class="phone-glass"><div class="phone-screen"></div></div></div>
        <div class="desk" id="m-desk"><div class="desk-bar"><i></i><i></i><i></i></div><div class="desk-view"></div></div>
      </div>

${cap("cap-a", "She asked a simple question.")}
${cap("cap-b", "She got homework.")}
${cap("cap-q", "What if the answer was the screen?", "centre", "top:560px;bottom:auto;")}
${cap("cap-r", "Polyxd turns the answer into a screen.")}
${cap("cap-app", "Any app.")}
${cap("cap-design", "In its own design.")}
${cap("cap-chk", "Checked before anyone sees it.")}
${cap("cap-m", "Any screen. Any design system.")}

      <div id="b4-outro" data-composition-id="outro-b" data-composition-src="assets/shared/outro-b.html" data-start="${T.outro}" data-duration="${+(T.end - T.outro).toFixed(3)}" data-track-index="1" data-variable-values='{"url":"polyxd.com"}'></div>

${bus("music", "Music", 1)}
${bus("sfx", "Sound design", 0.9, -8)}
      <audio id="b4-music" data-timeline-role="music" src="assets/music.wav" data-start="0" data-duration="${T.end}" data-track-index="10" data-volume="1" data-audio-group="music" data-fx-chain="${attr(musicChain)}" data-automation="${attr(musicAuto)}"></audio>
${audio}
    </div>
    <script>
      window.B4_T = ${JSON.stringify(T)};
      document.fonts.ready.then(() => {
        const tl = window.buildFilmB4();
        window.__timelines["film-b4"] = tl;
        if (window.__hfForceTimelineRebind) window.__hfForceTimelineRebind();
      });
    </script>
  </body>
</html>
`;
writeFileSync(`${DIR}/index.html`, html);
console.log(`wrote film-b4-return-the-shoes/index.html (${T.end} s, ${cues.length} sound cues)`);
