/**
 * Writes film-s-who-gives-ai-taste/index.html (and copies its assets) from
 * shared/film-s-timings.json. The story: STORY-STUDIO.md.
 *
 *   node apps/film/hyperframes/film-s-capture.mjs   (Studio's screens, from a local seeded Studio, once)
 *   node apps/film/hyperframes/music-s.mjs          (the score, once)
 *   node apps/film/hyperframes/make-s.mjs
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const DIR = here("film-s-who-gives-ai-taste");
const T = JSON.parse(readFileSync(here("shared/film-s-timings.json"), "utf8"));
delete T._;

const COPY = [
  ["../../../packages/web/preview/polyxd-web.js", "polyxd/polyxd-web.js"],
  ["../../../packages/web/preview/polyxd-web.css", "polyxd/polyxd-web.css"],
  ["shared/mark.js", "shared/mark.js"],
  ["shared/kit.js", "shared/kit.js"],
  ["shared/kit.css", "shared/kit.css"],
  ["shared/film-b.css", "shared/film-b.css"],
  ["shared/film-b4.css", "shared/film-b4.css"],
  ["shared/morph.js", "shared/morph.js"],
  ["shared/hw-kit.js", "shared/hw-kit.js"],
  ["shared/film-s.js", "shared/film-s.js"],
  ["shared/film-s.css", "shared/film-s.css"],
  ["shared/sting-b.html", "shared/sting-b.html"],
  ["shared/outro-b.html", "shared/outro-b.html"],
  ["../assets/fonts/YoungSerif-Regular.ttf", "fonts/YoungSerif-Regular.ttf"],
  ["../assets/fonts/DMMono-Regular.ttf", "fonts/DMMono-Regular.ttf"],
  ["../assets/fonts/HankenGrotesk-latin.woff2", "fonts/HankenGrotesk-latin.woff2"],
  ["film-b5-return-the-shoes/assets/fonts/Caveat-700-latin.woff2", "fonts/Caveat-700-latin.woff2"],
];
for (const [from, to] of COPY) {
  const dest = `${DIR}/assets/${to}`;
  mkdirSync(dest.slice(0, dest.lastIndexOf("/")), { recursive: true });
  copyFileSync(here(from), dest);
}

// ——— Studio's screens (film-s-capture.mjs): the boxes, the published screen, the crops ———
const STUDIO = `${DIR}/assets/studio`;
const BOXES = JSON.parse(readFileSync(`${STUDIO}/boxes.json`, "utf8"));
BOXES.pubPreview = { x: 557, y: 196, w: 646, h: 282 };
const CANCEL = JSON.parse(readFileSync(`${STUDIO}/cancel.json`, "utf8"));
mkdirSync(`${STUDIO}/crop`, { recursive: true });
const crop = (src, box, out) => {
  if (existsSync(`${STUDIO}/crop/${out}.png`)) return;
  const [x, y, w, h] = [box.x, box.y, box.w, box.h].map((v) => Math.round(v * 2));
  execFileSync("ffmpeg", ["-y", "-v", "error", "-i", `${STUDIO}/${src}.png`, "-vf", `crop=${w}:${h}:${x}:${y}`, `${STUDIO}/crop/${out}.png`]);
};
const pad = (b, p) => ({ x: b.x - p, y: b.y - p, w: b.w + 2 * p, h: b.h + 2 * p });
for (const h of BOXES.rb.frames) crop(`rb-${h}`, BOXES.rb.dialog, `rb-${h}`);
for (const n of BOXES.choiceSteps) crop(`choice-${String(n).padStart(2, "0")}`, pad(BOXES["choice-00"].use, 6), `choice-${String(n).padStart(2, "0")}`);
for (const n of BOXES.rule0Steps) crop(`rule0-${String(n).padStart(2, "0")}`, pad(BOXES["rule0-00"].name, 6), `rule0-${String(n).padStart(2, "0")}`);
crop("cancel-pub", BOXES.pubPreview, "pub-preview");
writeFileSync(`${DIR}/assets/s-data.js`, `/* Generated by make-s.mjs from assets/studio (film-s-capture.mjs). */\nwindow.S_BOXES = ${JSON.stringify(BOXES)};\nwindow.S_CANCEL = ${JSON.stringify(CANCEL)};\n`);

// ——— Themes: Harbourline as Studio exports it, and the assistant's loud version of it ———
// The loud one is Harbourline's own light theme with its brand hue turned to an off-brand blue,
// louder, tighter and squarer: what an assistant draws with no one's taste. The tune morph runs
// every token from it back to Harbourline's.
const css = readFileSync(`${STUDIO}/harbourline.css`, "utf8");
const light = css.slice(css.indexOf("[data-pxd-theme"), css.indexOf("}", css.indexOf("[data-pxd-theme")) + 1);
let loud = light.replace(/\[data-pxd-theme="harbourline"\]/g, '[data-pxd-theme="loud"]');
loud = loud.replace(/oklch\(([\d.]+)% ([\d.]+) 200(\s*\/\s*[\d.]+)?\)/g, (_, l, c, a) => `oklch(${l}% ${Math.min(0.3, parseFloat(c) * 1.35).toFixed(3)} 264${a || ""})`);
const set = (name, value) => {
  const re = new RegExp(`(${name}:\\s*)[^;]+;`);
  if (!re.test(loud)) throw new Error(`no ${name} in the export`);
  loud = loud.replace(re, `$1${value};`);
};
set("--pxd-color-status-info-background", "oklch(52% 0.26 264)");
set("--pxd-color-status-info-foreground", "#ffffff");
set("--pxd-color-action-primary-background", "oklch(52% 0.28 264)");
set("--pxd-space-inset-default", "10px");
set("--pxd-space-inset-comfortable", "12px");
set("--pxd-space-stack-default", "4px");
set("--pxd-space-stack-loose", "6px");
set("--pxd-space-stack-section", "12px");
set("--pxd-space-inline-default", "4px");
set("--pxd-radius-control", "3px");
set("--pxd-radius-default", "3px");
set("--pxd-radius-large", "4px");
set("--pxd-type-title-page-weight", "800");
set("--pxd-type-title-page-letter-spacing", "0.6px");
set("--pxd-type-label-default-letter-spacing", "0.8px");
writeFileSync(`${DIR}/assets/themes.css`, `/* Generated by make-s.mjs. Harbourline: Studio's CSS export (assets/studio/harbourline.css). */\n${css}\n\n/* The assistant's loud version of it (see make-s.mjs). */\n${loud}\n`);

// ——— Sound design: HeyGen audio catalogue effects, resolved through media-use (see .media/manifest.jsonl) ———
const SFX = {
  whoosh: [".media/audio/sfx/sfx_001.mp3", 0.22, 1.056], // Quick Whoosh (00caa739)
  hit: [".media/audio/sfx/sfx_002.mp3", 0.42, 3.058], // Cinematic Sub Bass Hit (128d8419)
  tap: [".media/audio/sfx/sfx_003.mp3", 0.04, 0.264], // Soft muted tap (19bd1766)
  pop: [".media/audio/sfx/sfx_004.mp3", 0.02, 0.576], // UI Pop (4558aa13)
  swish: [".media/audio/sfx/sfx_005.mp3", 0.08, 0.264], // Fast whoosh (72d0b143)
  paper: [".media/audio/sfx/sfx_006.mp3", 0.5, 1.008], // Page turn (9b77ef76): the pen on paper
  airy: [".media/audio/sfx/sfx_007.mp3", 0.6, 1.423], // Fast airy whoosh (a4855a82)
  typing: [".media/audio/sfx/sfx_008.mp3", 0.04, 2.326], // Keyboard Typing (e401e115)
  click: [".media/audio/sfx/sfx_009.mp3", 0.04, 0.192], // Sharp click (e7945ed1)
  chime: [".media/audio/sfx/sfx_010.mp3", 0.22, 1.334], // Bright electronic chime (ef870618)
  riser: [".media/audio/sfx/sfx_011.mp3", 2.08, 3.405], // Deep whoosh riser (f6995a68)
  toggle: [".media/audio/sfx/sfx_012.mp3", 0.1, 0.264], // Mechanical double click (ee5e8476)
  ding: [".media/audio/sfx/sfx_013.mp3", 0.03, 0.576], // High pitched chime (f6601811)
  sweep: [".media/audio/sfx/sfx_014.mp3", 0.32, 1.285], // Short synth whoosh (f21dfc94)
  stamp: [".media/audio/sfx/sfx_015.mp3", 0.45, 1.104], // Quick Swipe Impact (8639f575)
  land: [".media/audio/sfx/sfx_016.mp3", 0.65, 1.308], // Airy pop (d9b59db7)
};
const cue = (k, at, vol) => ({ k, start: +Math.max(0, at - SFX[k][1]).toFixed(3), vol });
const saved = [T.saved0, T.saved1, T.saved2];
const cues = [
  cue("whoosh", 0.62, 0.3),
  cue("swish", T.stageIn + 0.2, 0.22),
  cue("typing", T.typeFrom, 0.26),
  cue("tap", T.send, 0.45),
  ...[0, 1, 2, 3, 4, 5].map((i) => cue("pop", T.parts + i * T.partsEvery, 0.12)),
  cue("paper", T.c1On + 0.3, 0.2),
  cue("paper", T.a2On + 0.3, 0.18),
  cue("paper", T.s3On + 0.2, 0.2),
  cue("airy", T.tilt + 0.3, 0.28),
  cue("riser", T.capD, 0.22),
  cue("paper", T.arrowTurn + 0.3, 0.18),
  cue("airy", T.winIn + 0.35, 0.3),
  ...[0, 1, 2, 3].map((i) => cue("land", T.chip0 + i * T.chipEvery + 0.38, 0.2)),
  ...[0, 1, 2, 3, 4].map((i) => cue("click", T.count + 0.1 + i * 0.25, 0.22)),
  cue("swish", T.map + 0.2, 0.18),
  ...[0, 1, 2, 3, 4, 5].map((i) => cue("click", T.tick0 + i * T.tickEvery + 0.12, 0.2)),
  cue("paper", T.rolesNote + 0.2, 0.16),
  cue("swish", T.tune + 0.2, 0.2),
  cue("pop", T.dlgOpen, 0.2),
  cue("sweep", T.sweep + 0.3, 0.26),
  cue("sweep", T.sweep + 1.5, 0.22),
  cue("paper", T.tagOn + 0.3, 0.18),
  cue("swish", T.pullTune + 0.2, 0.2),
  cue("toggle", T.tog1, 0.4),
  cue("toggle", T.tog2, 0.4),
  cue("toggle", T.tog3, 0.4),
  cue("pop", T.drawer, 0.18),
  cue("typing", T.guideType, 0.22),
  cue("paper", T.guideOn + 0.3, 0.18),
  cue("pop", T.rule0, 0.18),
  cue("typing", T.ruleType, 0.22),
  ...saved.flatMap((s) => [cue("tap", s, 0.35), cue("swish", s + 0.1, 0.2), cue("paper", s + T.fly + T.fixLag + 0.15, 0.16), cue("ding", s + T.fly + T.fixLag + 0.55, 0.2)]),
  cue("swish", T.author + 0.2, 0.2),
  cue("paper", T.hair + 0.2, 0.2),
  cue("paper", T.hair + 0.7, 0.14),
  cue("paper", T.arrowShell + 0.3, 0.16),
  cue("click", T.press + 0.14, 0.35),
  cue("stamp", T.published, 0.35),
  cue("hit", T.published, 0.16),
  cue("whoosh", T.devices + 0.3, 0.3),
  cue("typing", T.code, 0.2),
  ...[0, 1, 2, 3].map((i) => cue("pop", T.chips + i * T.chipsEvery, 0.14)),
  cue("whoosh", T.pubOut + 0.2, 0.26),
  cue("typing", T.typeFrom2, 0.26),
  cue("tap", T.send2, 0.45),
  ...[0, 1, 2, 3].map((i) => cue("pop", T.parts2 + i * T.parts2Every, 0.12)),
  cue("chime", T.markChecked, 0.3),
].sort((a, b) => a.start - b.start);
const audio = cues
  .map((c, i) => `      <audio id="s-sfx-${i}" src="${SFX[c.k][0]}" data-start="${c.start}" data-duration="${SFX[c.k][2]}" data-track-index="${12 + i}" data-volume="${c.vol}" data-audio-group="sfx"></audio>`)
  .join("\n");
const attr = (o) => JSON.stringify(o).replace(/"/g, "&quot;");
// The score: under everything; a small dip under the sting's hit, a lift into the payoff.
const musicAuto = {
  version: 1,
  lanes: [{ target: "volume", points: [{ t: 0, v: 0.9 }, { t: 0.45, v: 0.9 }, { t: 0.62, v: 0.72 }, { t: 1.6, v: 0.9 }, { t: T.publish, v: 0.92 }, { t: T.payoff, v: 1 }, { t: T.end, v: 1 }] }],
};
const bus = (id, label, vol, limit) => `      <hf-audio-group id="${id}" data-label="${label}" data-volume="${vol}" data-fx-chain="${attr({ version: 1, nodes: [{ type: "highpass", id: "n1", label: "Remove Rumble", params: { frequency: 30, q: 0.707, poles: "2" } }, ...(limit === undefined ? [] : [{ type: "limiter", id: "n2", label: "Ceiling", params: { limit, attack: 5, release: 80, level_out: 0 } }])] })}"></hf-audio-group>`;

const cap = (id, text, cls = "", style = "") =>
  `      <div id="${id}" class="b4cap ${cls}" style="${style}"><div class="mask" data-layout-allow-overflow><p class="line">${text
    .split(" ")
    .map((w) => `<span class="w">${w}</span>`)
    .join(" ")}</p></div></div>`;

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>Polyxd · Studio · Who gives AI taste?</title>
    <!-- Generated by apps/film/hyperframes/make-s.mjs from shared/film-s-timings.json. The story: STORY-STUDIO.md. -->
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <link rel="stylesheet" href="assets/polyxd/polyxd-web.css" />
    <link rel="stylesheet" href="assets/themes.css" />
    <link rel="stylesheet" href="assets/shared/kit.css" />
    <link rel="stylesheet" href="assets/shared/film-b.css" />
    <link rel="stylesheet" href="assets/shared/film-b4.css" />
    <link rel="stylesheet" href="assets/shared/film-s.css" />
    <style>
      @font-face { font-family: "Young Serif"; src: url("assets/fonts/YoungSerif-Regular.ttf") format("truetype"); font-weight: 400; font-style: normal; }
      @font-face { font-family: "Hanken Grotesk"; src: url("assets/fonts/HankenGrotesk-latin.woff2") format("woff2"); font-weight: 100 900; font-style: normal; }
      @font-face { font-family: "DM Mono"; src: url("assets/fonts/DMMono-Regular.ttf") format("truetype"); font-weight: 400; font-style: normal; }
      @font-face { font-family: "Caveat"; src: url("assets/fonts/Caveat-700-latin.woff2") format("woff2"); font-weight: 700; font-style: normal; font-display: block; }
      @font-face { font-family: "SFMono-Regular"; src: local("SFMono-Regular"), local("SF Mono"); }
    </style>
    <script src="assets/polyxd/polyxd-web.js"></script>
    <script src="assets/shared/mark.js"></script>
    <script src="assets/shared/kit.js"></script>
    <script src="assets/shared/morph.js"></script>
    <script src="assets/shared/hw-kit.js"></script>
    <script src="assets/s-data.js"></script>
    <script src="assets/shared/film-s.js"></script>
  </head>
  <body>
    <div id="root" data-composition-id="film-s" data-start="0" data-width="1920" data-height="1080" data-duration="${T.end}">
      <div id="s-sting" data-composition-id="sting-b" data-composition-src="assets/shared/sting-b.html" data-start="0" data-duration="${T.stingDur}" data-track-index="1"></div>

      <div id="turn">
        <div id="sticky" style="left:900px;top:290px;width:390px;height:350px;font-size:42px;transform:rotate(-4deg);"><div class="t">cancel screen</div>3 primary buttons?<br />“Oops!”?<br />not our blue</div>
        <div id="turn-mark2" style="left:1360px;top:240px;"></div>
        <div id="turn-ink"></div>
      </div>

      <div id="stageA" class="stage">
        <div class="persp">
          <div id="rigA" class="rig">
            <div id="studio-win" style="opacity:0" data-layout-allow-occlusion data-layout-allow-overflow>
              <div class="win-bar"><i></i><i></i><i></i><span data-layout-allow-occlusion data-layout-allow-overflow>studio.polyxd.com/w/harbourline</span></div>
              <div id="studio-view"><div id="sink"></div></div>
            </div>
          </div>
        </div>
      </div>

      <div id="panel"></div>

      <div id="stageB" class="stage">
        <div class="persp">
          <div id="rigB" class="rig">
            <div id="phonebox" style="opacity:0">
              <div class="phone"><div class="phone-glass"><div class="phone-screen" id="screen"></div></div></div>
              <div id="pink"></div>
            </div>
            <div class="seat" id="seat" style="opacity:0"></div>
          </div>
        </div>
      </div>

      <div id="devices">
        <div id="d-laptop"><div class="lscreen"><div class="lview"></div></div><div class="lbase"></div></div>
        <div id="d-phone"><div class="pscreen"><div class="pview"></div></div></div>
        <div id="d-code"></div>
      </div>

      <div id="fly"></div>

${cap("cap-a", "AI can draw any screen.")}
${cap("cap-b", "But who gives it taste?")}
${cap("cap-d", "Your designers do.")}
${cap("cap-e", "In Studio.")}
${cap("cap-f", "Bring your design system as it is.", "side")}
${cap("cap-g", "Tune it, and everything follows.", "side")}
${cap("cap-h", "Decide what screens may use.", "side")}
${cap("cap-i", "Write the rules in plain words.", "low")}
${cap("cap-j", "Every screen is checked against them.", "low")}
${cap("cap-k", "Author the screens that shouldn’t be generated.", "side")}
${cap("cap-l", "Publish it. Your products fetch it.", "side")}
${cap("cap-m", "Now the screen is yours.")}

      <div id="s-outro" data-composition-id="outro-b" data-composition-src="assets/shared/outro-b.html" data-start="${T.outro}" data-duration="${+(T.end - T.outro).toFixed(3)}" data-track-index="1" data-variable-values='{"url":"Polyxd Studio · studio.polyxd.com"}'></div>

${bus("music", "Music", 1)}
${bus("sfx", "Sound design", 0.9, -8)}
      <audio id="s-music" data-timeline-role="music" src="assets/music.wav" data-start="0" data-duration="${T.end}" data-track-index="10" data-volume="1" data-audio-group="music" data-automation="${attr(musicAuto)}"></audio>
${audio}
    </div>
    <script>
      window.S_T = ${JSON.stringify(T)};
      document.fonts.ready.then(() => {
        const tl = window.buildFilmS();
        window.__timelines["film-s"] = tl;
        if (window.__hfForceTimelineRebind) window.__hfForceTimelineRebind();
      });
    </script>
  </body>
</html>
`;
writeFileSync(`${DIR}/index.html`, html);
console.log(`wrote film-s-who-gives-ai-taste/index.html (${T.end} s, ${cues.length} sound cues)`);
