/**
 * Writes film-d2-where-is-my-order/index.html (and copies its assets) from shared/film-d2-timings.json.
 * The developer film, second cut (dark, one ask): STORY-DEV-2.md. Film D's generator (make-d.mjs), re-cut.
 *
 *   node apps/film/hyperframes/music-d2.mjs   (the score, once)
 *   node apps/film/hyperframes/make-d2.mjs
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const DIR = here("film-d2-where-is-my-order");
const T = JSON.parse(readFileSync(here("shared/film-d2-timings.json"), "utf8"));
delete T._;

const COPY = [
  ["../../../packages/web/preview/polyxd-web.js", "polyxd/polyxd-web.js"],
  ["../../../packages/web/preview/polyxd-web.css", "polyxd/polyxd-web.css"],
  ["shared/mark.js", "shared/mark.js"],
  ["shared/kit.js", "shared/kit.js"],
  ["shared/kit.css", "shared/kit.css"],
  ["shared/morph.js", "shared/morph.js"],
  ["shared/hw-kit.js", "shared/hw-kit.js"],
  ["shared/film-b4.css", "shared/film-b4.css"],
  ["shared/film-d2.css", "shared/film-d2.css"],
  ["shared/film-d2.js", "shared/film-d2.js"],
  ["shared/ascii-field.js", "shared/ascii-field.js"],
  ["shared/sting-ascii.html", "shared/sting-ascii.html"],
  ["shared/outro-ascii.html", "shared/outro-ascii.html"],
  // acme, as `npx polyxd pack ./acme.css --dark ./acme-dark.css` wrote it, compiled to CSS (see shared/film-d2-acme).
  ["shared/film-d2-acme/pack.css", "acme-pack.css"],
  ["../assets/fonts/YoungSerif-Regular.ttf", "fonts/YoungSerif-Regular.ttf"],
  ["../assets/fonts/DMMono-Regular.ttf", "fonts/DMMono-Regular.ttf"],
  ["../assets/fonts/HankenGrotesk-latin.woff2", "fonts/HankenGrotesk-latin.woff2"],
  ["film-b5-return-the-shoes/assets/fonts/Caveat-700-latin.woff2", "fonts/Caveat-700-latin.woff2"],
];
for (const [from, to] of COPY) {
  const dest = `${DIR}/assets/${to}`;
  mkdirSync(dest.slice(0, dest.lastIndexOf("/")), { recursive: true });
  copyFileSync(here(from), dest);
}
// Strip the renderer's CSS transitions: they run on the browser clock, so a render worker could capture
// a state change half-way. The film poses every state on its own timeline instead.
{
  const css = `${DIR}/assets/polyxd/polyxd-web.css`;
  writeFileSync(css, readFileSync(css, "utf8").replace(/transition:[^;}]*;?/g, ""));
}
// The order document (shop-order-status.json plus one Action and order.id) and one spec example per issue.
const ORDER = JSON.parse(readFileSync(here("shared/film-d2-order/order-status.json"), "utf8"));
const NAMES = [
  "crm-cancel-subscription", "settings-api-keys", "travel-booking-review", "crm-accounts-list", "money-send-form",
  "money-balance-overview", "crm-account-record", "money-budget-settings", "shop-compare-plans", "team-members",
  "shop-browse-filter", "shop-checkout", "storage-usage", "calendar-find-slot", "settings-notifications",
  "settings-delete-account", "tasks-list", "tasks-add", "travel-flight-results",
];
const docs = Object.fromEntries(NAMES.map((n) => [n, JSON.parse(readFileSync(here(`../../../packages/spec/examples/${n}.json`), "utf8"))]));
// The order's two items: the owner's photos (.media/images), cropped square on the product, inlined as
// data URIs and handed to the renderer through resolveMedia for the document's image refs.
const CROPS = { img_lamp: ["desk-lamp", "330:330:225:205"], img_bulbs: ["led-bulbs", "360:360:15:220"] };
const media = {};
mkdirSync(`${DIR}/assets/images`, { recursive: true });
for (const [ref, [name, crop]] of Object.entries(CROPS)) {
  const out = `${DIR}/assets/images/${name}.jpg`;
  execFileSync("ffmpeg", ["-v", "error", "-y", "-i", `${DIR}/.media/images/${name}.png`, "-vf", `crop=${crop},scale=512:512:flags=lanczos`, "-q:v", "3", out]);
  media[ref] = `data:image/jpeg;base64,${readFileSync(out).toString("base64")}`;
}
writeFileSync(`${DIR}/assets/film-d2-docs.js`, `/* Generated by make-d2.mjs from packages/spec/examples, shared/film-d2-order and .media/images. */\nwindow.D_DOCS = ${JSON.stringify(docs)};\nwindow.D_ORDER = ${JSON.stringify(ORDER)};\nwindow.D_MEDIA = ${JSON.stringify(media)};\n`);

// Sound design: film D's HeyGen catalogue effects, ingested into this project through media-use.
// [file, seconds to the effect's peak, length]
const SFX = {
  slap: [".media/audio/sfx/sfx_001.mp3", 0.37, 1.1], // Quick Swipe Impact (8639f575)
  page: [".media/audio/sfx/sfx_002.mp3", 0.5, 1.0], // Page turn (9b77ef76)
  typing: [".media/audio/sfx/sfx_003.mp3", 0.02, 2.52], // Keyboard typing (fa6fa6ac)
  key: [".media/audio/sfx/sfx_004.mp3", 0.03, 0.26], // Sharp mechanical click (eada0ef7)
  swish: [".media/audio/sfx/sfx_005.mp3", 0.1, 0.29], // Fast Whoosh (5ae247cc)
  whoosh: [".media/audio/sfx/sfx_006.mp3", 0.5, 1.58], // Fast synthetic whoosh (68ce3485)
  hit: [".media/audio/sfx/sfx_007.mp3", 0.34, 4.9], // Sub bass impact (494a9f44)
  riser: [".media/audio/sfx/sfx_008.mp3", 1.92, 4.97], // Synthetic Sweeping Riser (3c4358ca)
  pop: [".media/audio/sfx/sfx_009.mp3", 0.03, 0.58], // UI Pop (4558aa13)
  land: [".media/audio/sfx/sfx_010.mp3", 0.56, 1.3], // Airy pop (d9b59db7)
  chime: [".media/audio/sfx/sfx_011.mp3", 0.04, 0.72], // Digital notification chime (fd8d6893)
  sparkle: [".media/audio/sfx/sfx_012.mp3", 0.72, 3.33], // Ascending chime sparkle (7a885578)
  ratchet: [".media/audio/sfx/sfx_013.mp3", 0.09, 0.65], // Rapid Mechanical Clicks (162db4c9)
  tap: [".media/audio/sfx/sfx_014.mp3", 0.16, 0.24], // Short Click (cf8c57bb)
  click: [".media/audio/sfx/sfx_015.mp3", 0.07, 0.26], // Sharp click (7e44f651)
};
const cue = (k, at, vol, dur) => ({ k, start: +Math.max(0, at - SFX[k][1]).toFixed(3), vol, dur: dur || SFX[k][2] });
const flurryAt = (i) => T.flurry + i * T.flurryEvery;
// The payoff's flips, as film-d2.js times them.
const flipAt = (i) => T.flip1 + T.flipSpan * Math.pow(i / 18, 0.62);
const cues = [
  cue("whoosh", 0.62, 0.22),
  // The backlog: a soft slap per issue, the flurry a rattle of them.
  ...[T.r1, T.r2, T.r3, T.r4].map((t) => cue("slap", t + 0.06, 0.34)),
  ...Array.from({ length: 16 }, (_, i) => cue("slap", flurryAt(i) + 0.05, i % 2 ? 0.1 : 0.15)),
  cue("page", T.plus + 0.25, 0.14),
  // The turn: under water, a riser into the drop.
  cue("swish", T.veil, 0.18),
  cue("tap", T.blink, 0.1),
  cue("riser", T.hit - 0.06, 0.34),
  cue("swish", T.peel + 0.1, 0.24),
  cue("hit", T.hit, 0.42),
  // 1 · Describe it.
  cue("typing", T.json, 0.2, T.jsonTo - T.json + 0.2),
  ...[T.a1, T.a2, T.a3].flatMap((a) => [cue("page", a + 0.35, 0.11), cue("pop", a + 0.58, 0.2)]),
  cue("pop", T.btnIn + 0.22, 0.16),
  // 2 · Style it.
  cue("swish", T.swap + 0.1, 0.22),
  cue("typing", T.tsx, 0.18, T.tsxTo - T.tsx),
  cue("page", T.circleP + 0.2, 0.12),
  ...[T.carbon, T.shadcn, T.govuk, T.terminal, T.brutalist].flatMap((a) => [cue("typing", a, 0.14, 0.5), cue("swish", a + 0.62, 0.16)]),
  cue("swish", T.deskIn, 0.16),
  cue("swish", T.pane, 0.16),
  cue("typing", T.pack, 0.18, T.packEnter - T.pack),
  cue("key", T.packEnter, 0.3),
  cue("typing", T.acme, 0.16, 0.6),
  cue("whoosh", T.acme + 0.85, 0.24),
  cue("chime", T.acme + 1.45, 0.16),
  // 3 · Wire it.
  cue("swish", T.poseR + 0.2, 0.16),
  cue("tap", T.press + 0.18, 0.5),
  cue("swish", T.card + 0.15, 0.2),
  cue("land", T.cardLand, 0.32),
  cue("page", T.circleS + 0.2, 0.1),
  // 4 · Trust it.
  cue("whoosh", T.down + 0.35, 0.3),
  cue("typing", T.verify, 0.18, T.verifyEnter - T.verify),
  cue("key", T.verifyEnter, 0.3),
  cue("pop", T.grid + 0.15, 0.12),
  cue("pop", T.grid + 0.45, 0.1),
  cue("sparkle", T.wave + 0.15, 0.16),
  cue("click", T.verifyOut, 0.22),
  cue("page", T.circle100 + 0.2, 0.1),
  // Payoff: home, the cards flip, To Do runs to zero.
  cue("whoosh", T.journey + 0.4, 0.34),
  cue("land", T.journey + 1.0, 0.18),
  ...[0, 1, 2].map((i) => cue("swish", flipAt(i) + 0.05, 0.18)),
  ...[0, 1, 2, 4, 7, 10, 13, 16].map((i) => cue("pop", flipAt(i) + 0.9 - i * 0.02, i < 3 ? 0.14 : 0.1)),
  cue("sparkle", flipAt(8), 0.14),
  cue("click", T.cleared + 0.1, 0.26),
  cue("chime", T.final, 0.18),
  ...Array.from({ length: 6 }, (_, i) => cue("key", T.final + 0.4 + i * 0.17, 0.08)),
].sort((a, b) => a.start - b.start);
const audio = cues
  .map((c, i) => `      <audio id="d-sfx-${i}" src="${SFX[c.k][0]}" data-start="${c.start}" data-duration="${+c.dur.toFixed(3)}" data-track-index="${12 + i}" data-volume="${c.vol}" data-audio-group="sfx"></audio>`)
  .join("\n");
const attr = (o) => JSON.stringify(o).replace(/"/g, "&quot;");
// The score: under everything. A low-pass closes over the turn and opens on the drop.
const musicAuto = {
  version: 1,
  lanes: [
    { target: "volume", points: [{ t: 0, v: 0.9 }, { t: 0.45, v: 0.9 }, { t: 0.62, v: 0.74 }, { t: 1.6, v: 0.9 }, { t: T.hit - 0.1, v: 0.9 }, { t: T.hit, v: 1 }, { t: T.final - 0.2, v: 1 }, { t: T.final, v: 0.85 }, { t: T.final + 1.2, v: 1 }] },
  ],
};
const bus = (id, label, vol, limit) => `      <hf-audio-group id="${id}" data-label="${label}" data-volume="${vol}" data-fx-chain="${attr({ version: 1, nodes: [{ type: "highpass", id: "n1", label: "Remove Rumble", params: { frequency: 30, q: 0.707, poles: "2" } }, ...(limit === undefined ? [] : [{ type: "limiter", id: "n2", label: "Ceiling", params: { limit, attack: 5, release: 80, level_out: 0 } }])] })}"></hf-audio-group>`;

// A caption: words revealed one by one; " / " breaks a line.
const cap = (id, text, cls = "", style = "") =>
  `      <div id="${id}" class="b4cap ${cls}" style="${style}"><div class="mask" data-layout-allow-overflow><p class="line">${text
    .split(" / ")
    .map((l) => l.split(" ").map((w) => `<span class="w">${w}</span>`).join(" "))
    .join("<br />")}</p></div></div>`;

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>Polyxd · D2 · Where’s my order?</title>
    <!-- Generated by apps/film/hyperframes/make-d2.mjs from shared/film-d2-timings.json. The story: STORY-DEV-2.md. -->
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <link rel="stylesheet" href="assets/polyxd/polyxd-web.css" />
    <link rel="stylesheet" href="assets/acme-pack.css" />
    <link rel="stylesheet" href="assets/shared/kit.css" />
    <link rel="stylesheet" href="assets/shared/film-b4.css" />
    <link rel="stylesheet" href="assets/shared/film-d2.css" />
    <style>
      @font-face { font-family: "Young Serif"; src: url("assets/fonts/YoungSerif-Regular.ttf") format("truetype"); font-weight: 400; font-style: normal; }
      @font-face { font-family: "Hanken Grotesk"; src: url("assets/fonts/HankenGrotesk-latin.woff2") format("woff2"); font-weight: 100 900; font-style: normal; }
      @font-face { font-family: "DM Mono"; src: url("assets/fonts/DMMono-Regular.ttf") format("truetype"); font-weight: 400; font-style: normal; font-display: block; }
      @font-face { font-family: "Caveat"; src: url("assets/fonts/Caveat-700-latin.woff2") format("woff2"); font-weight: 700; font-style: normal; font-display: block; }
      @font-face { font-family: "SFMono-Regular"; src: local("SFMono-Regular"), local("SF Mono"); }
    </style>
    <script src="assets/polyxd/polyxd-web.js"></script>
    <script src="assets/shared/mark.js"></script>
    <script src="assets/shared/kit.js"></script>
    <script src="assets/shared/morph.js"></script>
    <script src="assets/shared/hw-kit.js"></script>
    <script src="assets/shared/ascii-field.js"></script>
    <script src="assets/film-d2-docs.js"></script>
    <script src="assets/shared/film-d2.js"></script>
  </head>
  <body>
    <svg width="0" height="0" style="position:absolute" aria-hidden="true"><filter id="d-whip" x="-10%" y="-10%" width="120%" height="120%"><feGaussianBlur id="d-blur" stdDeviation="0 0" /></filter></svg>
    <div id="root" data-composition-id="film-d2" data-start="0" data-width="1920" data-height="1080" data-duration="${T.end}">
      <div id="d-sting" data-composition-id="sting-ascii" data-composition-src="assets/shared/sting-ascii.html" data-start="0" data-duration="${T.stingDur}" data-track-index="1"></div>

      <div id="d-ground"></div>
      <div id="world" class="group">
        <div id="persp">
          <div id="rig"><div id="ink"></div></div>
        </div>
      </div>

      <div id="d-veil"></div>
      <div id="d-turn-mark"></div>
      <div id="d-vignette"></div>
      <div id="d-scrim"></div>
      <div id="d-lscrim"></div>
      <div id="d-fly"><div class="t"><i class="od"></i><div class="a">Where’s my order? Show tracking in the app</div><div class="b">#933 · feature request · 👍 214</div></div></div>

${cap("cap-1", "Your users ask / for more than / you’ll ever build.", "dnarrow")}
${cap("cap-2", "What if every ask came with its screen?", "centre", "top:660px;bottom:auto;")}
${cap("cap-3", "You or your agent / describe the screen. / Polyxd draws it.", "dnarrow")}
      <div id="d-mcp" class="d2-sub">MCP server: mcp.polyxd.com/mcp</div>
${cap("cap-4", "Any design system. / Including yours.", "dnarrow")}
${cap("cap-5", "Your code / decides / what it does.", "dnarrow")}
${cap("cap-6", "Checked before / anyone sees it.", "dnarrow")}
${cap("cap-7", "Every ask / gets a screen.", "dnarrow", "left:120px;width:540px;")}

      <div id="d-outro" data-composition-id="outro-ascii" data-composition-src="assets/shared/outro-ascii.html" data-start="${T.outro}" data-duration="${+(T.end - T.outro).toFixed(3)}" data-track-index="1" data-variable-values='${JSON.stringify({ url: "polyxd.com/docs · open source", dur: +(T.end - T.outro).toFixed(3), blink: +(T.final - T.outro).toFixed(3) })}'></div>

${bus("music", "Music", 0.955)}
${bus("sfx", "Sound design", 0.81, -8)}
      <audio id="d-music" data-timeline-role="music" src="assets/music.wav" data-start="0" data-duration="91.34" data-track-index="10" data-volume="1" data-audio-group="music" data-automation="${attr(musicAuto)}"></audio>
${audio}
    </div>
    <script>
      window.D_T = ${JSON.stringify(T)};
      Promise.all(["30px 'DM Mono'", "700 50px Caveat", "78px 'Young Serif'", "600 20px 'Hanken Grotesk'"].map((f) => document.fonts.load(f))).then(() => document.fonts.ready).then(() => {
        const tl = window.buildFilmD2();
        window.__timelines["film-d2"] = tl;
        if (window.__hfForceTimelineRebind) window.__hfForceTimelineRebind();
      });
    </script>
  </body>
</html>
`;
writeFileSync(`${DIR}/index.html`, html);
console.log(`wrote film-d2-where-is-my-order/index.html (${T.end} s, ${cues.length} sound cues)`);
