/**
 * Writes film-d-ship-the-screen/index.html (and copies its assets) from shared/film-d-timings.json.
 * The developer film: STORY-DEV.md.
 *
 *   node apps/film/hyperframes/music-d.mjs   (the score, once)
 *   node apps/film/hyperframes/make-d.mjs
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const DIR = here("film-d-ship-the-screen");
const T = JSON.parse(readFileSync(here("shared/film-d-timings.json"), "utf8"));
delete T._;

const COPY = [
  ["../../../packages/web/preview/polyxd-web.js", "polyxd/polyxd-web.js"],
  ["../../../packages/web/preview/polyxd-web.css", "polyxd/polyxd-web.css"],
  ["shared/mark.js", "shared/mark.js"],
  ["shared/kit.js", "shared/kit.js"],
  ["shared/kit.css", "shared/kit.css"],
  ["shared/morph.js", "shared/morph.js"],
  ["shared/hw-kit.js", "shared/hw-kit.js"],
  ["shared/film-b4.css", "shared/film-b4.css"],
  ["shared/film-d.css", "shared/film-d.css"],
  ["shared/film-d.js", "shared/film-d.js"],
  ["shared/sting-b.html", "shared/sting-b.html"],
  ["shared/outro-b.html", "shared/outro-b.html"],
  // The pack `npx polyxd pack ./acme.css` wrote, as `npx polyxd dev --pack` compiled it (see the README).
  ["shared/film-d-acme/pack.css", "acme-pack.css"],
  ["../assets/fonts/YoungSerif-Regular.ttf", "fonts/YoungSerif-Regular.ttf"],
  ["../assets/fonts/DMMono-Regular.ttf", "fonts/DMMono-Regular.ttf"],
  ["../assets/fonts/HankenGrotesk-latin.woff2", "fonts/HankenGrotesk-latin.woff2"],
];
for (const [from, to] of COPY) {
  const dest = `${DIR}/assets/${to}`;
  mkdirSync(dest.slice(0, dest.lastIndexOf("/")), { recursive: true });
  copyFileSync(here(from), dest);
}
// The spec's examples, as published: the confirm step, and one screen for each note on the board.
const NAMES = [
  "money-send-confirm", "calendar-find-slot", "settings-notifications", "money-balance-overview",
  "money-budget-settings", "money-send-form", "shop-order-status", "shop-compare-plans", "shop-browse-filter", "shop-checkout", "tasks-add",
  "tasks-list", "tasks-delete-project", "travel-flight-results", "travel-booking-review", "travel-trip-overview",
  "team-members", "settings-api-keys", "settings-delete-account", "storage-usage", "personal-reading-log", "personal-habits",
];
const docs = Object.fromEntries(NAMES.map((n) => [n, JSON.parse(readFileSync(here(`../../../packages/spec/examples/${n}.json`), "utf8"))]));
writeFileSync(`${DIR}/assets/film-d-docs.js`, `/* Generated by make-d.mjs from packages/spec/examples. */\nwindow.D_DOCS = ${JSON.stringify(docs)};\n`);

// Sound design: HeyGen audio catalogue effects, frozen through media-use (see .media/manifest.jsonl).
// [file, seconds to the effect's peak, length]
const SFX = {
  slap: [".media/audio/sfx/sfx_001.mp3", 0.37, 1.1], // Quick Swipe Impact (8639f575)
  page: [".media/audio/sfx/sfx_002.mp3", 0.5, 1.0], // Page turn (9b77ef76)
  typing: [".media/audio/sfx/sfx_003.mp3", 0.02, 2.52], // Keyboard typing (fa6fa6ac)
  key: [".media/audio/sfx/sfx_004.mp3", 0.03, 0.26], // Sharp mechanical click (eada0ef7)
  swish: [".media/audio/sfx/sfx_005.mp3", 0.1, 0.29], // Fast Whoosh (5ae247cc)
  whoosh: [".media/audio/sfx/sfx_006.mp3", 0.5, 1.58], // Fast synthetic whoosh (68ce3485)
  hit: [".media/audio/sfx/sfx_007.mp3", 0.34, 4.9], // Sub bass impact (494a9f44)
  riser: [".media/audio/sfx/sfx_008.mp3", 1.92, 4.97], // Synthetic Sweeping Riser (3c4358ca)
  pop: [".media/audio/sfx/sfx_009.mp3", 0.03, 0.58], // UI Pop (4558aa13)
  land: [".media/audio/sfx/sfx_010.mp3", 0.56, 1.3], // Airy pop (d9b59db7)
  chime: [".media/audio/sfx/sfx_011.mp3", 0.04, 0.72], // Digital notification chime (fd8d6893)
  sparkle: [".media/audio/sfx/sfx_012.mp3", 0.72, 3.33], // Ascending chime sparkle (7a885578)
  ratchet: [".media/audio/sfx/sfx_013.mp3", 0.09, 0.65], // Rapid Mechanical Clicks (162db4c9)
  tap: [".media/audio/sfx/sfx_014.mp3", 0.16, 0.24], // Short Click (cf8c57bb)
  click: [".media/audio/sfx/sfx_015.mp3", 0.07, 0.26], // Sharp click (7e44f651)
};
const cue = (k, at, vol, dur) => ({ k, start: +Math.max(0, at - SFX[k][1]).toFixed(3), vol, dur: dur || SFX[k][2] });
const flurryAt = (i) => T.flurry + i * T.flurryEvery;
const cues = [
  cue("whoosh", 0.62, 0.22),
  // The backlog: a slap per note, the pile a rattle of them.
  ...[T.n1, T.n2, T.n3, T.n4].map((t) => cue("slap", t + 0.08, 0.42)),
  ...Array.from({ length: 20 }, (_, i) => cue("slap", flurryAt(i) + 0.06, i % 2 ? 0.12 : 0.18)),
  cue("page", T.plus + 0.25, 0.14),
  // The turn: under water, a riser into the drop.
  cue("swish", T.veil, 0.18),
  cue("tap", T.blink, 0.1),
  cue("riser", T.hit - 0.06, 0.34),
  cue("swish", T.peel + 0.1, 0.24),
  cue("hit", T.hit, 0.42),
  // A screen is a document.
  cue("typing", T.json, 0.2, T.jsonTo - T.json + 0.2),
  ...[T.a1, T.a2, T.a3].flatMap((a) => [cue("page", a + 0.35, 0.11), cue("pop", a + 0.58, 0.2)]),
  cue("swish", T.pushC + 0.2, 0.18),
  cue("page", T.under + 0.2, 0.1),
  // One component.
  cue("swish", T.swap + 0.1, 0.22),
  cue("typing", T.npm, 0.2, T.npmEnter - T.npm),
  cue("key", T.npmEnter, 0.3),
  cue("typing", T.tsx, 0.18, T.tsxTo - T.tsx),
  cue("page", T.circleP + 0.2, 0.12),
  ...[T.carbon, T.govuk, T.shadcn].flatMap((a) => [cue("typing", a, 0.16, 0.6), cue("whoosh", a + 0.85, 0.2)]),
  // Your code decides.
  cue("swish", T.poseR + 0.2, 0.16),
  cue("tap", T.press + 0.18, 0.5),
  cue("swish", T.card + 0.15, 0.2),
  cue("land", T.cardLand, 0.32),
  cue("page", T.circleS + 0.2, 0.1),
  // Checked.
  cue("whoosh", T.down + 0.35, 0.3),
  cue("typing", T.val, 0.18, 0.62),
  cue("key", T.valOut - 0.15, 0.3),
  cue("page", T.valTick + 0.1, 0.12),
  cue("typing", T.verify, 0.18, T.verifyEnter - T.verify),
  cue("key", T.verifyEnter, 0.3),
  cue("pop", T.grid + 0.15, 0.12),
  cue("pop", T.grid + 0.45, 0.1),
  cue("sparkle", T.wave + 0.15, 0.16),
  cue("click", T.verifyOut, 0.22),
  cue("page", T.circle100 + 0.2, 0.1),
  cue("whoosh", T.agent + 0.45, 0.28),
  cue("ratchet", T.scan + 0.05, 0.24),
  cue("ratchet", T.scan + 0.6, 0.24),
  cue("tap", T.agentPress + 0.05, 0.45),
  cue("chime", T.agentEvent, 0.26),
  // Your design system.
  cue("whoosh", T.whip1 + 0.31, 0.32),
  cue("typing", T.pack, 0.18, T.packEnter - T.pack),
  cue("key", T.packEnter, 0.3),
  cue("page", T.circlePack + 0.2, 0.12),
  cue("typing", T.dev, 0.18, T.devEnter - T.dev),
  cue("key", T.devEnter, 0.3),
  cue("swish", T.browser + 0.1, 0.2),
  cue("chime", T.browser + 0.5, 0.24),
  cue("pop", T.squig + 0.1, 0.12),
  cue("typing", T.squigFix, 0.14, 0.35),
  cue("click", T.squigFix + 0.5, 0.2),
  // Not React.
  cue("whoosh", T.whip2 + 0.31, 0.32),
  cue("typing", T.html, 0.18, T.htmlTo - T.html),
  cue("swish", T.twin + 0.3, 0.18),
  cue("page", T.same + 0.2, 0.12),
  cue("click", T.same + 0.95, 0.24),
  // Payoff: home, the notes flip, the board clears.
  cue("whoosh", T.journey + 0.4, 0.34),
  cue("land", T.journey + 1.0, 0.18),
  ...[0, 1, 2].map((i) => cue("page", T.flip1 + i * 0.35 + 0.1, 0.18)),
  ...[0, 1, 2, 3, 4].map((i) => cue("page", T.wave2 + i * 0.2 + 0.1, 0.12)),
  cue("sparkle", T.wave2 + 0.5, 0.14),
  cue("whoosh", T.ship + 0.25, 0.3),
  cue("click", T.ship + 0.85, 0.26),
  cue("chime", T.outro + 1.25, 0.2),
].sort((a, b) => a.start - b.start);
const audio = cues
  .map((c, i) => `      <audio id="d-sfx-${i}" src="${SFX[c.k][0]}" data-start="${c.start}" data-duration="${+c.dur.toFixed(3)}" data-track-index="${12 + i}" data-volume="${c.vol}" data-audio-group="sfx"></audio>`)
  .join("\n");
const attr = (o) => JSON.stringify(o).replace(/"/g, "&quot;");
// The score: under everything. A low-pass closes over the turn and opens on the drop.
const musicChain = { version: 1, nodes: [{ type: "lowpass", id: "n1", label: "Turn filter", params: { frequency: 18000, q: 0.707, poles: "2" } }] };
const musicAuto = {
  version: 1,
  lanes: [
    { target: "fx.n1.frequency", points: [{ t: 0, v: 18000 }, { t: T.veil, v: 18000 }, { t: T.veil + 0.8, v: 1100, curve: -0.4 }, { t: T.hit - 0.8, v: 1500 }, { t: T.hit - 0.02, v: 18000 }] },
    { target: "volume", points: [{ t: 0, v: 0.9 }, { t: 0.45, v: 0.9 }, { t: 0.62, v: 0.74 }, { t: 1.6, v: 0.9 }, { t: T.hit - 0.1, v: 0.9 }, { t: T.hit, v: 1 }, { t: T.final - 0.2, v: 1 }, { t: T.final, v: 0.85 }, { t: T.final + 1.2, v: 1 }] },
  ],
};
const bus = (id, label, vol, limit) => `      <hf-audio-group id="${id}" data-label="${label}" data-volume="${vol}" data-fx-chain="${attr({ version: 1, nodes: [{ type: "highpass", id: "n1", label: "Remove Rumble", params: { frequency: 30, q: 0.707, poles: "2" } }, ...(limit === undefined ? [] : [{ type: "limiter", id: "n2", label: "Ceiling", params: { limit, attack: 5, release: 80, level_out: 0 } }])] })}"></hf-audio-group>`;

const cap = (id, text, cls = "", style = "") =>
  `      <div id="${id}" class="b4cap ${cls}" style="${style}"><div class="mask" data-layout-allow-overflow><p class="line">${text
    .split(" ")
    .map((w) => `<span class="w">${w}</span>`)
    .join(" ")}</p></div></div>`;

const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1920, height=1080" />
    <title>Polyxd · D · Ship the screen, not the backlog</title>
    <!-- Generated by apps/film/hyperframes/make-d.mjs from shared/film-d-timings.json. The story: STORY-DEV.md. -->
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <link rel="stylesheet" href="assets/polyxd/polyxd-web.css" />
    <link rel="stylesheet" href="assets/acme-pack.css" />
    <link rel="stylesheet" href="assets/shared/kit.css" />
    <link rel="stylesheet" href="assets/shared/film-b4.css" />
    <link rel="stylesheet" href="assets/shared/film-d.css" />
    <style>
      @font-face { font-family: "Young Serif"; src: url("assets/fonts/YoungSerif-Regular.ttf") format("truetype"); font-weight: 400; font-style: normal; }
      @font-face { font-family: "Hanken Grotesk"; src: url("assets/fonts/HankenGrotesk-latin.woff2") format("woff2"); font-weight: 100 900; font-style: normal; }
      @font-face { font-family: "DM Mono"; src: url("assets/fonts/DMMono-Regular.ttf") format("truetype"); font-weight: 400; font-style: normal; font-display: block; }
      @font-face { font-family: "Caveat"; src: url("assets/fonts/Caveat-700-latin.woff2") format("woff2"); font-weight: 700; font-style: normal; font-display: block; }
      @font-face { font-family: "SFMono-Regular"; src: local("SFMono-Regular"), local("SF Mono"); }
    </style>
    <script src="assets/polyxd/polyxd-web.js"></script>
    <script src="assets/shared/mark.js"></script>
    <script src="assets/shared/kit.js"></script>
    <script src="assets/shared/morph.js"></script>
    <script src="assets/shared/hw-kit.js"></script>
    <script src="assets/film-d-docs.js"></script>
    <script src="assets/shared/film-d.js"></script>
  </head>
  <body>
    <svg width="0" height="0" style="position:absolute" aria-hidden="true"><filter id="d-whip" x="-10%" y="-10%" width="120%" height="120%"><feGaussianBlur id="d-blur" stdDeviation="0 0" /></filter></svg>
    <div id="root" data-composition-id="film-d" data-start="0" data-width="1920" data-height="1080" data-duration="${T.end}">
      <div id="d-sting" data-composition-id="sting-b" data-composition-src="assets/shared/sting-b.html" data-start="0" data-duration="${T.stingDur}" data-track-index="1"></div>

      <div id="world" class="group">
        <div id="persp">
          <div id="rig"><div id="ink"></div></div>
        </div>
      </div>

      <div id="d-veil"></div>
      <div id="d-turn-mark"></div>
      <div id="d-scrim"></div>
      <div id="d-fly"><div class="t">Pay Alex my rent share</div></div>

${cap("cap-1", "Your users ask for more than you’ll ever build.")}
${cap("cap-2", "What if a screen were just data?", "centre", "top:560px;bottom:auto;")}
${cap("cap-3", "A screen is a small document.", "dnarrow")}
${cap("cap-4", "Meaning, not pixels.", "dnarrow")}
${cap("cap-5", "One component draws it, in any design system.", "dtop")}
${cap("cap-6", "Your code decides what it does.", "dtop")}
${cap("cap-7", "The spec and the verifier check every screen.", "dnarrow")}
${cap("cap-8", "People and agents can use it.", "dtop")}
${cap("cap-9", "Your design system comes in with one command.", "dnarrow")}
${cap("cap-10", "Not React? The same screen as a web component.", "dnarrow")}
${cap("cap-11", "Ship the screen, not the backlog.", "centre dbig")}

      <div id="d-outro" data-composition-id="outro-b" data-composition-src="assets/shared/outro-b.html" data-start="${T.outro}" data-duration="${+(T.end - T.outro).toFixed(3)}" data-track-index="1" data-variable-values='{"url":"polyxd.com/docs · open source"}'></div>

${bus("music", "Music", 1.06)}
${bus("sfx", "Sound design", 0.9, -8)}
      <audio id="d-music" data-timeline-role="music" src="assets/music.wav" data-start="0" data-duration="97.5" data-track-index="10" data-volume="1" data-audio-group="music" data-fx-chain="${attr(musicChain)}" data-automation="${attr(musicAuto)}"></audio>
${audio}
    </div>
    <script>
      window.D_T = ${JSON.stringify(T)};
      Promise.all(["30px 'DM Mono'", "700 50px Caveat", "78px 'Young Serif'", "600 20px 'Hanken Grotesk'"].map((f) => document.fonts.load(f))).then(() => document.fonts.ready).then(() => {
        const tl = window.buildFilmD();
        window.__timelines["film-d"] = tl;
        if (window.__hfForceTimelineRebind) window.__hfForceTimelineRebind();
      });
    </script>
  </body>
</html>
`;
writeFileSync(`${DIR}/index.html`, html);
console.log(`wrote film-d-ship-the-screen/index.html (${T.end} s, ${cues.length} sound cues)`);
