/**
 * The montage near the end of film B: screens from the four demo products and the spec's
 * examples, each in its own design system, drawn by the real renderer. Writes a script the film
 * loads (no fetch at render time): window.MONTAGE = [{ frame, theme, name, doc }].
 *
 *   import { montage } from "./montage.mjs"  (sync.mjs calls it)
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const repo = (p) => fileURLToPath(new URL(`../../../${p}`, import.meta.url));
const demo = (p) => JSON.parse(readFileSync(repo(`apps/demos/${p}`), "utf8")).document;
const spec = (p) => JSON.parse(readFileSync(repo(`packages/spec/examples/${p}.json`), "utf8"));

/** Phone and desktop in turn; every one a different product or design system. */
export const SHOTS = [
  { frame: "phone", theme: "material3", name: "Halden · Budgets", doc: () => demo("halden/authored/screen.budgets.json") },
  { frame: "desk", theme: "polaris", name: "Quay · Why sales dropped", doc: () => demo("quay/intents/revenue.dip.json") },
  { frame: "phone", theme: "govuk", name: "Wexley · Bins", doc: () => demo("wexley/authored/screen.bins.json") },
  { frame: "desk", theme: "shadcn", name: "Foundry · Account overview", doc: () => demo("foundry/authored/screen.account.overview.json") },
  { frame: "phone", theme: "fluent", name: "Order #4821", doc: () => spec("shop-order-status") },
  { frame: "desk", theme: "carbon", name: "Choose a plan", doc: () => spec("shop-compare-plans") },
  { frame: "phone", theme: "primer", name: "Find a time", doc: () => spec("calendar-find-slot") },
  { frame: "desk", theme: "antd", name: "Acme Corp", doc: () => spec("crm-account-record") },
  { frame: "phone", theme: "spectrum", name: "Lisbon trip", doc: () => spec("travel-trip-overview") },
  { frame: "desk", theme: "mantine", name: "Storage", doc: () => spec("storage-usage") },
  { frame: "phone", theme: "radix", name: "Your balance", doc: () => spec("money-balance-overview") },
  { frame: "desk", theme: "bootstrap", name: "Notifications", doc: () => spec("settings-notifications") },
];

export function montage(count = SHOTS.length) {
  const list = SHOTS.slice(0, count).map(({ doc, ...s }) => ({ ...s, doc: doc() }));
  return `/* Generated by apps/film/hyperframes/montage.mjs from apps/demos and packages/spec/examples. */\nwindow.MONTAGE = ${JSON.stringify(list)};\n`;
}
