/**
 * What the generator is told about the spec, built from the spec itself so it can't drift: every
 * component a generated document may use with its props, and every pattern with its structure and
 * checks. Written as a module so the runtime needs no file system at run time (browsers, Workers).
 * A test fails when this file is out of date. Run with `npm run build:catalog -w @polyxd/runtime`.
 */
import { readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const SPEC = new URL("../../spec/", import.meta.url);
const OUT = new URL("../src/catalog.generated.ts", import.meta.url);
const read = async (p: string) => JSON.parse(await readFile(new URL(p, SPEC), "utf8"));

/** Short names for the schema's shared definitions, as the model reads them. */
const REF_NAMES: Record<string, string> = {
  DynamicString: "text|{path}",
  DynamicNumber: "number|{path}",
  DynamicBoolean: "bool|{path}",
  DynamicValue: "value|{path}",
  Binding: "{path}",
  Id: "id",
  Key: "key",
  Path: "path",
  Format: "{type:currency|number|percent|date|time|datetime|relativeTime|color|bytes,currency?}",
  Action: "{event:{name,context?}}",
  ActionSpec: "{label,action}",
  ChildList: "[ids]",
  Template: "{path,componentId}",
  Options: "[{value,label}]|{path,valuePath,labelPath}",
  Tone: "neutral|info|success|warning|danger",
  Accessibility: "{label?}",
};

function type(schema: any): string {
  if (schema.$ref) {
    const name = String(schema.$ref).split("/").pop()!;
    return REF_NAMES[name] ?? name;
  }
  if (schema.enum) return schema.enum.join("|");
  if (schema.type === "array") {
    const items = schema.items ?? {};
    if (items.type === "object") return `[{${Object.keys(items.properties ?? {}).map((k) => k + ((items.required ?? []).includes(k) ? "" : "?")).join(",")}}]`;
    return `[${type(items)}]`;
  }
  if (schema.type === "object") return `{${Object.keys(schema.properties ?? {}).map((k) => k + ((schema.required ?? []).includes(k) ? "" : "?")).join(",")}}`;
  return String(schema.type ?? "any");
}

/** The generated module's source text. */
export async function catalogSource(): Promise<string> {
  const componentFiles = (await readdir(new URL("components/", SPEC))).filter((f) => f.endsWith(".json")).sort();
  const components = (await Promise.all(componentFiles.map((f) => read(`components/${f}`)))).map((c) => ({
    name: c.name as string,
    // The shell components are the product's frame, authored once and never generated.
    shell: c.shell === true,
    line: `- ${c.name}(${Object.entries(c.props)
      .map(([name, s]) => `${name}${c.required.includes(name) ? "*" : ""}: ${type(s)}`)
      .join(", ")})\n  ${c.summary} Use for: ${c.whenToUse.slice(0, 2).join("; ")}.`,
  }));
  const patternFiles = (await readdir(new URL("patterns/", SPEC))).filter((f) => f.endsWith(".json")).sort();
  const patterns = (await Promise.all(patternFiles.map((f) => read(`patterns/${f}`)))).map((p) => ({
    id: p.id,
    name: p.name,
    summary: p.summary,
    whenToUse: p.whenToUse ?? [],
    structure: p.structure ?? [],
    checks: p.checks ?? [],
  }));
  const { SPEC_VERSION } = (await import(new URL("src/version.ts", SPEC).href)) as { SPEC_VERSION: string };
  return `// Generated by scripts/build-catalog.ts from the spec (${SPEC_VERSION}). Do not edit.
import type { CatalogComponent, CatalogPattern } from "./types.ts";

export const SPEC_VERSION = ${JSON.stringify(SPEC_VERSION)};

export const COMPONENTS: CatalogComponent[] = ${JSON.stringify(components, null, 1)};

export const PATTERNS: CatalogPattern[] = ${JSON.stringify(patterns, null, 1)};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const source = await catalogSource();
  await writeFile(OUT, source);
  console.log(`wrote src/catalog.generated.ts (${source.length} chars)`);
}
