// Generated by scripts/build-catalog.ts from the spec (0.3.0). Do not edit.
import type { CatalogComponent, CatalogPattern } from "./types.ts";

export const SPEC_VERSION = "0.3.0";

export const COMPONENTS: CatalogComponent[] = [
 {
  "name": "Action",
  "shell": false,
  "line": "- Action(label*: text|{path}, action*: {event:{name,context?}}, emphasis: primary|secondary|tertiary, tone: default|danger, disabled: bool|{path}, description: text|{path}, copy: text|{path}, shortcut: string)\n  A button that triggers a host capability. Use for: Anything the user can do that isn't typing or choosing."
 },
 {
  "name": "ActionBar",
  "shell": false,
  "line": "- ActionBar(children*: [ids])\n  The set of actions for a surface or section; the renderer places it where that platform expects. Use for: Two or more actions that apply to the whole surface or section."
 },
 {
  "name": "ActionMenu",
  "shell": false,
  "line": "- ActionMenu(label*: text|{path}, kind: overflow|dropdown|split|context, children*: [ids], primary: id)\n  Secondary actions behind one control: an overflow menu, a dropdown, a split button or a context menu. Use for: Three or more secondary actions on a row, a card or a page header; One usual action with rarer alternatives (split: 'Save' with 'Save as draft')."
 },
 {
  "name": "AppBar",
  "shell": true,
  "line": "- AppBar(title*: text|{path}, brand: text|{path}, leading: id, search: id, actions: id, account: id, variant: standard|large|compact, sticky: boolean)\n  The bar at the top of the product: brand or title, a leading action, search, trailing actions and the account. Use for: The header region of a Frame; A product that needs a persistent place for search, notifications and the account."
 },
 {
  "name": "Card",
  "shell": false,
  "line": "- Card(title*: text|{path}, subtitle: text|{path}, media: id, badge: {text,tone?}, children: [ids], action: {event:{name,context?}}, progress: {value,label?})\n  One self-contained entity (an account, an order, a place), optionally actionable as a whole. Use for: Items in a Collection that each represent an entity; A single entity summary in a larger surface."
 },
 {
  "name": "Chart",
  "shell": false,
  "line": "- Chart(intent*: trend|comparison|composition|distribution|relationship|flow|hierarchy|matrix|range, data*: {path}, title*: text|{path}, summary*: text|{path}, x*: {path,label,format?}, series*: [{key?,path,label,format?}])\n  A visual summary of data, always paired with a text summary. Use for: A trend, comparison, share or spread matters more than exact values."
 },
 {
  "name": "Choice",
  "shell": false,
  "line": "- Choice(label*: text|{path}, options*: [{value,label}]|{path,valuePath,labelPath}, value*: {path}, mode: single|multiple, help: text|{path}, required: boolean)\n  Pick one or several options from a known set. The renderer chooses the control. Use for: Any choice from a known set of options."
 },
 {
  "name": "Code",
  "shell": false,
  "line": "- Code(text*: text|{path}, label: text|{path}, language: string, copyable: boolean, wrap: boolean, secret: bool|{path})\n  Code, a command or preformatted text, shown as written and copyable. Use for: A command to run, a snippet to paste, an identifier to copy; Structured text whose spacing matters."
 },
 {
  "name": "CodeInput",
  "shell": false,
  "line": "- CodeInput(label*: text|{path}, value*: {path}, length: integer, kind: numeric|alphanumeric, help: text|{path}, required: bool|{path}, action: {event:{name,context?}})\n  A one-time code or PIN, typed into one box per character. Use for: A verification code from email or SMS; A PIN or a short recovery code."
 },
 {
  "name": "Collection",
  "shell": false,
  "line": "- Collection(items*: {path,componentId}, label*: text|{path}, empty: id, selection: none|single|multiple, selected: {path}, layout: auto|list|grid|timeline|carousel|calendar, datePath: path, page: {index?,size?,total?,action?}, bulkActions: id, reorderable: boolean, order: {path})\n  A list of items from host data, each rendered with the same template. Use for: Browsing a set of similar entities; Search results."
 },
 {
  "name": "ColorInput",
  "shell": false,
  "line": "- ColorInput(label*: text|{path}, value*: {path}, swatches: [{value,label}]|{path,valuePath,labelPath}, format: hex|rgb|hsl, alpha: boolean, help: text|{path}, required: bool|{path})\n  Pick a colour: from swatches the host offers, or any colour. Use for: A colour for a label, a tag, a calendar, a theme; Choosing from a set of brand colours."
 },
 {
  "name": "Columns",
  "shell": false,
  "line": "- Columns(children*: [ids], layout: two-thirds|one-third|halves|thirds|sidebar-start|sidebar-end, collapse: compact|medium|never, align: start|center|stretch)\n  Side-by-side columns that collapse to a stack on compact layouts: a main column with a narrower one beside it, or equal halves. Use for: A form with help beside it; a record with a summary beside it; a list beside a preview; Anywhere a wide screen should use its width without the compact screen paying for it."
 },
 {
  "name": "Comparison",
  "shell": false,
  "line": "- Comparison(items*: {path}, itemTitle*: path, attributes*: [{key,label,path,format?,better?,group?}], choose: {label,action}, recommended: text|{path}, summary: text|{path}, recommendedReason: text|{path})\n  Compare a few options across the same attributes, and choose one. Use for: Choosing between 2–4 plans, products, routes or offers."
 },
 {
  "name": "Confirm",
  "shell": false,
  "line": "- Confirm(title*: text|{path}, message: text|{path}, consequence: text|{path}, summary: id, severity*: consequential|destructive, confirm*: {label,action}, cancel: {label,action}, typeToConfirm: text|{path}, amount: {value,format?}, subject: {title,subtitle?,avatar?}, consequences: [{title,detail?,icon?}])\n  Asks the user to confirm a consequential or destructive action, showing what will happen. Use for: Moving money, deleting data, sending on someone's behalf, anything irreversible."
 },
 {
  "name": "Custom",
  "shell": true,
  "line": "- Custom(name*: string, props: {}, fallback*: id, label: text|{path})\n  A slot for a component the host implements itself: a logo, a brand moment, a bespoke widget. The document names it and gives it props; the product renders it, and a fallback stands in when it can't. Use for: The parts of a product that are truly its own: a logo, an illustration system, a map, a chart type the spec doesn't have; Only in authored documents: a shell or a screen a person wrote for that product."
 },
 {
  "name": "DateInput",
  "shell": false,
  "line": "- DateInput(label*: text|{path}, value*: {path}, kind: date|time|datetime|dateRange|month|year, multiple: boolean, min: text|{path}, max: text|{path}, help: text|{path}, required: boolean)\n  A date, time, date-time or date range. Use for: Any date or time entry."
 },
 {
  "name": "DetailList",
  "shell": false,
  "line": "- DetailList(items*: [{key?,label,value,format?,total?}], title: text|{path}, variant: default|receipt, layout: rows|grid, rowAction: {event:{name,context?}})\n  Label/value pairs describing one thing (a summary, a receipt, a review step). Use for: Reviewing before submitting; Showing the attributes of one entity."
 },
 {
  "name": "Disclosure",
  "shell": false,
  "line": "- Disclosure(summary*: text|{path}, children*: [ids], open: boolean)\n  Progressive disclosure: secondary content hidden behind a toggle. Use for: Details most people don't need (fees breakdown, advanced options, help text)."
 },
 {
  "name": "FileInput",
  "shell": false,
  "line": "- FileInput(label*: text|{path}, value*: {path}, accept: [string], multiple: boolean, maxSize: integer, help: text|{path}, required: bool|{path})\n  Choose or drop files to attach or upload. Use for: Attaching a document, a receipt, a photo; Importing a file the product reads."
 },
 {
  "name": "FilterPanel",
  "shell": false,
  "line": "- FilterPanel(label: text|{path}, children*: [ids], results*: id, resultCount: {path}, clear: {event:{name,context?}})\n  Filters for a list of results, with the result count. Use for: Browsing results people narrow by several attributes; More than two filters, or filters that take space (ranges, long lists)."
 },
 {
  "name": "Footer",
  "shell": true,
  "line": "- Footer(groups: [{key,label,items}], legal*: text|{path}, aside: id)\n  The bar at the bottom of the product: link groups, the legal line, locale or status. Use for: The footer region of a Frame; Public services and marketing-adjacent products where legal and help links belong at the bottom."
 },
 {
  "name": "Form",
  "shell": false,
  "line": "- Form(children*: [ids], submit*: {label,action}, cancel: {label,action}, aside: id, layout: stacked|horizontal)\n  Collects inputs and submits them together. Use for: Any set of inputs that are submitted together."
 },
 {
  "name": "Frame",
  "shell": true,
  "line": "- Frame(header: id, navigation: id, main*: id, aside: id, footer: id, banner: id, skipTarget: boolean, width: full|contained)\n  The product's frame: the regions around its screens (header, navigation, main, aside, footer, banner), with an outlet where screens and generated surfaces appear. Use for: The root of a shell document: the product's frame, authored once, that every screen sits in; A product whose navigation, header and footer should render in its design system like everything else."
 },
 {
  "name": "Group",
  "shell": false,
  "line": "- Group(children*: [ids], label: text|{path}, arrangement: auto|inline|grid)\n  Visually groups closely related items without a heading (proximity). Use for: A few items that belong together (a key figure and its caption, several metrics)."
 },
 {
  "name": "Identity",
  "shell": false,
  "line": "- Identity(name*: text|{path}, detail: text|{path}, image: text|{path}, kind: person|team|organization, size: small|default|large, action: {event:{name,context?}}, group: {path,namePath,imagePath?,max?})\n  A person, team or organisation: picture, name and details, or several of them together. Use for: Who something belongs to, was sent by or is assigned to; The recipient on a payment, the owner on a record, the members on a team."
 },
 {
  "name": "Media",
  "shell": false,
  "line": "- Media(src: {path}, alt: text|{path}, decorative: boolean, aspect: square|landscape|portrait|auto, kind: image|video|audio|gallery|qr, poster: text|{path}, transcript: text|{path}, items: {path}, imagePath: path, altPath: path, value: text|{path})\n  An image, video, audio clip, gallery or QR code supplied by the host. Use for: Photos or illustrations that help identify something (a product, a place, a person); A recording people play, or a code they scan."
 },
 {
  "name": "Metric",
  "shell": false,
  "line": "- Metric(label*: text|{path}, value*: {path}, format: {type:currency|number|percent|date|time|datetime|relativeTime|color|bytes,currency?}, change: {value,format?,favorable?}, caption: text|{path})\n  A key figure with a label, and optionally its change. Use for: One to four headline numbers the user asked about."
 },
 {
  "name": "Navigation",
  "shell": false,
  "line": "- Navigation(label: text|{path}, items*: [{key,label,group?,icon?,badge?,action}], current*: {path}, kind: main|breadcrumb|nested|toc|local, placement: auto|side|rail|bar|drawer)\n  The product's main navigation. Use for: Software with sections people move between (B2B apps, dashboards); Only when the host doesn't already provide navigation."
 },
 {
  "name": "Outlet",
  "shell": true,
  "line": "- Outlet(label: text|{path}, loading: id)\n  Where the current screen renders inside a Frame: the host fills it with a screen document or a generated surface. Use for: The main region of a Frame."
 },
 {
  "name": "Panel",
  "shell": false,
  "line": "- Panel(kind: dialog|drawer|sheet|popover, title*: text|{path}, children*: [ids], actions: id, open: bool|{path}, dismissible: boolean, size: small|default|large)\n  Content over the current view: a dialog, a drawer, a bottom sheet or a popover, opened from an action and dismissed to return. Use for: A short task on top of the page: edit one thing, pick one thing, see one record; Detail the person asked for that shouldn't replace where they are."
 },
 {
  "name": "Progress",
  "shell": false,
  "line": "- Progress(label*: text|{path}, value*: number|{path}, max: number|{path}, kind: bar|ring|meter, caption: text|{path}, format: {type:currency|number|percent|date|time|datetime|relativeTime|color|bytes,currency?}, tone: neutral|info|success|warning|danger, thresholds: {warning?,danger?}, indeterminate: bool|{path})\n  How far along something is, or how much of a bounded amount is used: a bar, a ring or a meter. Use for: A task that takes time, with a known share done; How much of a quota, budget or capacity is used."
 },
 {
  "name": "RangeInput",
  "shell": false,
  "line": "- RangeInput(label*: text|{path}, value*: {path}, min*: number, max*: number, step: number, format: {type:currency|number|percent|date|time|datetime|relativeTime|color|bytes,currency?}, mode: single|range)\n  A number, or a range between two numbers, within known bounds. Use for: Approximate values within a range (budget cap, volume); A price or date range for filtering (mode 'range')."
 },
 {
  "name": "Rating",
  "shell": false,
  "line": "- Rating(label*: text|{path}, value*: {path}, max: integer, readOnly: bool|{path}, count: number|{path}, help: text|{path}, required: bool|{path}, action: {event:{name,context?}})\n  A score out of N: given by the person, or shown as others gave it. Use for: Asking how something went, out of five; Showing a product's or place's rating with the count behind it."
 },
 {
  "name": "Section",
  "shell": false,
  "line": "- Section(title*: text|{path}, description: text|{path}, children*: [ids])\n  A titled region of the surface that groups related content under a heading. Use for: The surface has two or more distinct topics (e.g. 'Recipient' and 'Amount'); Content would otherwise exceed one screen and needs signposting."
 },
 {
  "name": "Split",
  "shell": false,
  "line": "- Split(primary*: id, detail*: id, selected*: {path}, empty: id, ratio: narrow|balanced|wide, resizable: boolean)\n  Master and detail side by side: a list that stays while the chosen item's detail shows beside it; on compact layouts the detail replaces the list. Use for: Mail, tickets, messages, files: a list people move through while reading; Settings with many sections on wide screens."
 },
 {
  "name": "Status",
  "shell": false,
  "line": "- Status(kind*: info|success|warning|error|empty|loading|undo, title*: text|{path}, message: text|{path}, action: id, icon: lock|trash|clock|tag|info|alert|mail|shield|search|book|inbox|check, variant: default|inline)\n  Feedback about state: info, success, warning, error, empty or loading. Use for: Results of an action; Empty collections."
 },
 {
  "name": "Steps",
  "shell": false,
  "line": "- Steps(steps*: [{key,title,content,status?}], kind: wizard|tasklist|guide, current: number|{path}, finish*: {label,action})\n  A task split into ordered steps with visible progress. Use for: Tasks with dependent stages or too many inputs for one view (checkout, onboarding)."
 },
 {
  "name": "Table",
  "shell": false,
  "line": "- Table(rows*: {path}, caption*: text|{path}, columns*: [{key,label,path,format?,kind?,align?,tones?,sortable?,avatarPath?,secondaryPath?}], rowAction: {event:{name,context?}}, empty: id, sort: {column,direction?,action?}, selection: none|multiple, selected: {path}, rowValuePath: path, bulkActions: id, rowActions: id, expandable: boolean, detail: id, toolbar: id, search: id, views: [{key,label,count?,action?}], view: {path}, page: {index?,size?,total?,action?})\n  Tabular data: many items sharing the same attributes. Use for: Scanning or comparing many rows by several attributes; Records people scan, sort, select and act on in bulk (B2B lists)."
 },
 {
  "name": "Tag",
  "shell": false,
  "line": "- Tag(label*: text|{path}, kind: label|status|count, tone: neutral|info|success|warning|danger, count: number|{path}, remove: {event:{name,context?}})\n  A short label, status or count attached to something else. Use for: The state of a record, next to its name: 'Past due', 'Draft', 'Live'; A category or label a thing carries."
 },
 {
  "name": "Text",
  "shell": false,
  "line": "- Text(text*: text|{path}, variant: body|supporting|caption|rich|list|quote, format: {type:currency|number|percent|date|time|datetime|relativeTime|color|bytes,currency?}, items: {path}, itemPath: path, ordered: boolean, cite: text|{path})\n  A run of text. Use for: Explanations, instructions, messages."
 },
 {
  "name": "TextInput",
  "shell": false,
  "line": "- TextInput(label*: text|{path}, value*: {path}, kind: text|multiline|number|currency|email|phone|url|search|suggestions|richtext|tags|mentions|code|masked|inline, options: [{value,label}]|{path,valuePath,labelPath}, mask: string, currency: text|{path}, help: text|{path}, required: boolean, validation: {min?,max?,minLength?,maxLength?,message?}, autocomplete: string, placeholder: text|{path}, size: default|hero)\n  A single text-like value: text, number, email, phone, currency, search or long text. Use for: Free-form values the user types."
 },
 {
  "name": "Toggle",
  "shell": false,
  "line": "- Toggle(label*: text|{path}, value*: {path}, description: text|{path}, action: {event:{name,context?}})\n  An on/off setting. Use for: Settings that take effect immediately; A single yes/no inside a form."
 },
 {
  "name": "Tree",
  "shell": false,
  "line": "- Tree(label*: text|{path}, items*: {path}, labelPath*: path, childrenPath*: path, valuePath: path, detailPath: path, selection: none|single|multiple, selected: {path}, expanded: {path}, action: {event:{name,context?}})\n  A hierarchy people expand, browse and pick from: folders, an org chart, nested categories. Use for: Things that contain things: folders and files, an organisation, nested categories; Picking a place in a hierarchy (move to folder, choose a category)."
 },
 {
  "name": "Views",
  "shell": false,
  "line": "- Views(views*: [{key,label,content,count?}], selected: {path}, variant: tabs|segmented)\n  Switch between alternative views of the same subject (tabs). Use for: 2–6 peer views of the same data (Overview / Transactions / Settings)."
 }
];

export const PATTERNS: CatalogPattern[] = [
 {
  "id": "compare-and-choose",
  "name": "Compare and choose",
  "summary": "Put a few options side by side on the same attributes, mark what is better, recommend when there's a clear fit, and let the user choose.",
  "whenToUse": [
   "Choosing between 2–4 plans, products, routes or offers"
  ],
  "structure": [
   "Comparison with attributes in the same order for every option",
   "Optional recommendation with a one-line reason",
   "A choose action per option"
  ],
  "checks": [
   {
    "id": "one-comparison",
    "description": "Exactly one Comparison",
    "severity": "error",
    "rule": {
     "check": "contains",
     "component": "Comparison",
     "min": 1,
     "max": 1
    }
   },
   {
    "id": "can-choose",
    "description": "Each option can be chosen",
    "severity": "error",
    "rule": {
     "check": "requires",
     "component": "Comparison",
     "props": [
      "choose"
     ]
    }
   },
   {
    "id": "explains",
    "description": "A one-line summary or the recommendation's reason helps the decision",
    "severity": "warning",
    "rule": {
     "check": "anyOf",
     "checks": [
      {
       "check": "requires",
       "component": "Comparison",
       "props": [
        "summary"
       ]
      },
      {
       "check": "requires",
       "component": "Comparison",
       "props": [
        "recommendedReason"
       ]
      }
     ]
    }
   }
  ]
 },
 {
  "id": "confirm-destructive",
  "name": "Confirm a consequential or destructive action",
  "summary": "Before something that is hard or impossible to undo, say exactly what will happen and ask for an explicit, specific confirmation.",
  "whenToUse": [
   "Moving money",
   "Deleting data or accounts",
   "Sending or publishing on someone's behalf",
   "Any capability with risk level 'consequential' or 'destructive'"
  ],
  "structure": [
   "Confirm (title names the action and object)",
   "Consequence: what happens and whether it can be undone",
   "Optional DetailList summary of what is being confirmed",
   "Cancel (least destructive, focused first) and a confirm button that repeats the verb"
  ],
  "checks": [
   {
    "id": "root-is-confirm",
    "description": "The surface is a confirmation dialog",
    "severity": "error",
    "rule": {
     "check": "rootIs",
     "components": [
      "Confirm"
     ]
    }
   },
   {
    "id": "states-consequence",
    "description": "It says what will happen and whether it can be undone",
    "severity": "error",
    "rule": {
     "check": "requires",
     "component": "Confirm",
     "props": [
      "consequence"
     ]
    }
   },
   {
    "id": "specific-confirm-label",
    "description": "The confirm button says what it does, never just 'OK' or 'Yes'",
    "severity": "error",
    "rule": {
     "check": "noLabelMatches",
     "pattern": "^(OK|Ok|Yes|Confirm|Submit|Done)$"
    }
   },
   {
    "id": "typed-for-destructive",
    "description": "Irreversible, high-impact deletions ask the user to type a confirmation",
    "severity": "warning",
    "rule": {
     "check": "requires",
     "component": "Confirm",
     "where": {
      "severity": "destructive"
     },
     "props": [
      "typeToConfirm"
     ]
    }
   }
  ]
 },
 {
  "id": "filter-and-browse",
  "name": "Filter and browse",
  "summary": "Narrow a large set with a few filters placed before the results, and explain empty results.",
  "whenToUse": [
   "Searching or browsing many items"
  ],
  "structure": [
   "Filters (search, Choice, RangeInput) before the results",
   "Result count in the results label",
   "Collection or Table of results with an empty state that says how to widen the search"
  ],
  "checks": [
   {
    "id": "has-results",
    "description": "Results are shown as a Collection or Table",
    "severity": "error",
    "rule": {
     "check": "anyOf",
     "checks": [
      {
       "check": "contains",
       "component": "Collection"
      },
      {
       "check": "contains",
       "component": "Table"
      }
     ]
    }
   },
   {
    "id": "filters-first",
    "description": "Filters come before the results",
    "severity": "error",
    "rule": {
     "check": "precedes",
     "before": [
      "TextInput",
      "Choice",
      "RangeInput",
      "DateInput"
     ],
     "after": [
      "Collection",
      "Table"
     ]
    }
   },
   {
    "id": "empty-state",
    "description": "Empty results explain what to do",
    "severity": "error",
    "rule": {
     "check": "allOf",
     "checks": [
      {
       "check": "requires",
       "component": "Collection",
       "props": [
        "empty"
       ]
      },
      {
       "check": "requires",
       "component": "Table",
       "props": [
        "empty"
       ]
      }
     ]
    }
   }
  ]
 },
 {
  "id": "multi-step-form",
  "name": "Multi-step form",
  "summary": "Collect information in small, ordered chunks: one form when short, Steps when long or dependent.",
  "whenToUse": [
   "Any data entry task",
   "Tasks whose later questions depend on earlier answers"
  ],
  "structure": [
   "Form (≤ 6 inputs) or Steps with one topic per step",
   "Labels above inputs, help text under labels",
   "Verb-first submit label as the single primary action"
  ],
  "checks": [
   {
    "id": "form-or-steps",
    "description": "Inputs are collected in a Form or in Steps",
    "severity": "error",
    "rule": {
     "check": "anyOf",
     "checks": [
      {
       "check": "contains",
       "component": "Form"
      },
      {
       "check": "contains",
       "component": "Steps"
      }
     ]
    }
   },
   {
    "id": "short-views",
    "description": "No more than 6 inputs are visible at once; longer tasks are split into steps",
    "severity": "error",
    "rule": {
     "check": "maxInputsPerView",
     "max": 6
    }
   },
   {
    "id": "specific-submit",
    "description": "The submit button says what happens next",
    "severity": "warning",
    "rule": {
     "check": "noLabelMatches",
     "pattern": "^(OK|Ok|Yes|Confirm|Submit|Done)$"
    }
   }
  ]
 },
 {
  "id": "review-and-submit",
  "name": "Review and submit",
  "summary": "Before committing, show everything that will be submitted in a scannable summary, then one clear submit action.",
  "whenToUse": [
   "Bookings, orders, applications: any multi-field commitment"
  ],
  "structure": [
   "Sections with DetailLists summarising what will be submitted",
   "Any final acknowledgements (terms)",
   "Submit label states the commitment ('Book and pay £312')"
  ],
  "checks": [
   {
    "id": "has-summary",
    "description": "What will be submitted is shown as label/value pairs",
    "severity": "error",
    "rule": {
     "check": "contains",
     "component": "DetailList"
    }
   },
   {
    "id": "submits",
    "description": "There is a way to submit",
    "severity": "error",
    "rule": {
     "check": "anyOf",
     "checks": [
      {
       "check": "contains",
       "component": "Form"
      },
      {
       "check": "contains",
       "component": "Steps"
      }
     ]
    }
   },
   {
    "id": "summary-before-inputs",
    "description": "Review content comes before any last inputs",
    "severity": "warning",
    "rule": {
     "check": "anyOf",
     "checks": [
      {
       "check": "not",
       "checks": [
        {
         "check": "contains",
         "component": "Toggle"
        }
       ]
      },
      {
       "check": "precedes",
       "before": [
        "DetailList"
       ],
       "after": [
        "Toggle"
       ]
      }
     ]
    }
   },
   {
    "id": "commitment-label",
    "description": "The submit label states the commitment, not 'Submit'",
    "severity": "error",
    "rule": {
     "check": "noLabelMatches",
     "pattern": "^(OK|Ok|Yes|Confirm|Submit|Done|Continue)$"
    }
   }
  ]
 },
 {
  "id": "undo-over-confirm",
  "name": "Undo instead of confirm",
  "summary": "For everyday actions that can be reversed, do them straight away and offer Undo, instead of asking 'Are you sure?' every time.",
  "whenToUse": [
   "Archiving, removing from a list, marking done, moving to trash",
   "Any capability with risk 'none' or 'low' that names an 'undo' capability"
  ],
  "structure": [
   "The action runs when chosen",
   "Status (kind 'undo') says what happened, naming the thing",
   "Its action is Undo, wired to the reversing capability"
  ],
  "checks": [
   {
    "id": "has-undo-status",
    "description": "An undo notice says what happened",
    "severity": "error",
    "rule": {
     "check": "contains",
     "component": "Status",
     "where": {
      "kind": "undo"
     },
     "min": 1
    }
   },
   {
    "id": "undo-has-action",
    "description": "The notice offers Undo",
    "severity": "error",
    "rule": {
     "check": "requires",
     "component": "Status",
     "where": {
      "kind": "undo"
     },
     "props": [
      "action"
     ]
    }
   },
   {
    "id": "no-confirm",
    "description": "Nothing asks for confirmation first",
    "severity": "warning",
    "rule": {
     "check": "not",
     "checks": [
      {
       "check": "contains",
       "component": "Confirm"
      }
     ]
    }
   }
  ]
 }
];
