/**
 * Copies what the server serves from elsewhere in the repository into src/, so the published
 * package needs nothing outside itself:
 *
 *   src/packs.generated.ts        every design-system pack: name, display name, and whether it is a template
 *   src/spec-files.generated.ts   @polyxd/spec's component definitions, example documents and example
 *                                 Design Directions, imported as JSON modules so the server needs no
 *                                 file system (it runs in a Cloudflare Worker too)
 *   src/docs.generated.ts         the polyxd.com docs (apps/site/content/docs), for polyxd_docs, with
 *                                 site links made absolute
 *
 *   node scripts/sync.ts           write it
 *   node scripts/sync.ts --check   exit 1 if it is out of date (the tests run the same comparison)
 */
import { readdirSync, readFileSync, existsSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const REPO = new URL("../../../", import.meta.url);
const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const read = (p: string) => readFileSync(new URL(p, REPO), "utf8");

/** Same test as apps/site/scripts/check-docs.ts: a template's provenance names Polyxd, a real system's names the system. */
const isTemplate = (m: any) =>
  m?.template === true || (Array.isArray(m.provenance) ? m.provenance : [m.provenance]).some((e: any) => e?.template === true || /^Original template/.test(String(e?.notes ?? "")));

export function expected(): Record<string, string> {
  const dirs = readdirSync(new URL("packages/", REPO))
    .filter((d) => d.startsWith("ds-") && existsSync(new URL(`packages/${d}/manifest.json`, REPO)))
    .sort();
  const themes = new Set(readdirSync(new URL("packages/react/themes/", REPO)).map((f) => f.replace(/\.css$/, "")));
  const packs = dirs
    .map((d) => {
      const m = JSON.parse(read(`packages/${d}/manifest.json`));
      const pkg = JSON.parse(read(`packages/${d}/package.json`));
      const template = isTemplate(m);
      const description = String(pkg.description).replace(/ for Polyxd \(DTCG [^)]*\)/, "");
      return { name: m.name as string, displayName: m.displayName as string, template, package: pkg.name as string, description };
    })
    .filter((p) => themes.has(p.name));
  // Material 3 first: it is the default.
  packs.sort((a, b) => Number(b.name === "material3") - Number(a.name === "material3") || Number(a.template) - Number(b.template) || a.name.localeCompare(b.name));
  const packsFile = `// Generated by scripts/sync.ts from packages/ds-*/manifest.json. Do not edit.
export interface Pack {
  /** The pack's name: the theme the renderer applies. */
  name: string;
  displayName: string;
  /** An original design to start from, rather than a published design system. */
  template: boolean;
  /** The npm package with the pack's tokens. */
  package: string;
  description: string;
}

export const PACKS: Pack[] = ${JSON.stringify(packs, null, 2)};
`;
  return { [here("../src/packs.generated.ts")]: packsFile, [here("../src/spec-files.generated.ts")]: specFiles(), [here("../src/docs.generated.ts")]: docsFile() };
}

/** Import statements for every JSON file the server serves from @polyxd/spec, in a stable order. */
function specFiles(): string {
  const list = (dir: string) => readdirSync(new URL(`packages/spec/${dir}/`, REPO)).filter((f) => f.endsWith(".json")).sort();
  const groups = [
    { name: "COMPONENT_FILES", dir: "components", prefix: "c" },
    { name: "EXAMPLE_FILES", dir: "examples", prefix: "e" },
    { name: "DIRECTION_FILES", dir: "examples/directions", prefix: "d" },
  ].map((g) => ({ ...g, files: list(g.dir) }));
  const imports = groups.flatMap((g) => g.files.map((f, i) => `import ${g.prefix}${i} from "@polyxd/spec/${g.dir}/${f}" with { type: "json" };`));
  const lists = groups.map((g) => `export const ${g.name}: [file: string, json: unknown][] = [\n${g.files.map((f, i) => `  [${JSON.stringify(f)}, ${g.prefix}${i}],`).join("\n")}\n];`);
  return `// Generated by scripts/sync.ts from @polyxd/spec's components/ and examples/. Do not edit.
// Imported as JSON modules rather than read from disk, so the server runs where there is no file system.
${imports.join("\n")}

${lists.join("\n\n")}
`;
}

export const SITE = "https://polyxd.com";

/** Every docs page as Markdown: front matter read, the page's own "# Title" dropped, site links absolute. */
function docsFile(): string {
  const dir = new URL("apps/site/content/docs/", REPO);
  const pages = readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => {
      const src = readFileSync(new URL(f, dir), "utf8");
      const fm = /^---\n([\s\S]*?)\n---\n?/.exec(src);
      const meta: Record<string, string> = Object.fromEntries(
        (fm?.[1] ?? "").split("\n").map((l) => /^(\w+):\s*(.*)$/.exec(l)).filter((m): m is RegExpExecArray => !!m).map((m) => [m[1], m[2].replace(/^["']|["']$/g, "")]),
      );
      const slug = f === "index.md" ? "" : f.replace(/\.md$/, "");
      const markdown = src
        .slice(fm ? fm[0].length : 0)
        .replace(/^\s*# .*\n+/, "")
        .replace(/\]\(\/(?!\/)/g, `](${SITE}/`)
        .trim();
      return { slug, title: meta.title ?? slug, description: meta.description ?? "", section: meta.section ?? "Concepts", order: Number(meta.order ?? 50), url: `${SITE}/docs/${slug ? `${slug}/` : ""}`, markdown };
    })
    .sort((a, b) => a.order - b.order || a.slug.localeCompare(b.slug));
  return `// Generated by scripts/sync.ts from apps/site/content/docs. Do not edit.
export interface DocPage {
  /** The page's path under /docs/: "" for the docs home, "quickstart", … */
  slug: string;
  title: string;
  description: string;
  section: string;
  order: number;
  /** The page on polyxd.com. */
  url: string;
  /** The page's Markdown, without its title, with site links made absolute. */
  markdown: string;
}

export const DOCS: DocPage[] = ${JSON.stringify(pages, null, 2)};
`;
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  let stale = 0;
  for (const [path, content] of Object.entries(expected())) {
    const now = existsSync(path) ? readFileSync(path, "utf8") : "";
    if (now === content) continue;
    stale++;
    if (check) console.error(`${path} is out of date: run node scripts/sync.ts`);
    else writeFileSync(path, content), console.log(`wrote ${path}`);
  }
  if (check && stale) process.exit(1);
  if (!stale) console.log("up to date");
}
