/**
 * Compiles the schemas the package validates at run time into plain ES modules, with Ajv's
 * standalone output: the UI document schema (src/validate.ts) and the pattern file schema with the
 * checks it refers to (src/patterns.ts). Ajv normally compiles a schema when the package loads,
 * which generates code from strings; Cloudflare Workers and pages with a strict content security
 * policy forbid that. The generated modules do the same checks and report the same errors, and
 * need nothing from Ajv at run time.
 *
 * build-schema.ts writes them with everything else (`npm run build:schema`), and the tests fail
 * when they are stale or disagree with Ajv compiling the same schema at run time.
 */
import { readFile } from "node:fs/promises";
import { Ajv2020, type Options } from "ajv/dist/2020.js";
import standaloneModule from "ajv/dist/standalone/index.js";

const root = new URL("../", import.meta.url);
const read = async (p: string) => JSON.parse(await readFile(new URL(p, root), "utf8"));
const standaloneCode = ((standaloneModule as unknown as { default?: typeof standaloneModule }).default ?? standaloneModule) as typeof standaloneModule;

/** The options every validator is compiled with. Tests compile with these too, to compare. */
export const AJV_OPTIONS: Options = { allErrors: true, discriminator: true, strict: false };

/** A module exporting one validator for `schemas[0]`; the other schemas are the ones it refers to. */
function validatorModule(name: string, schemas: Record<string, any>[], from: string): string {
  const ajv = new Ajv2020({ ...AJV_OPTIONS, code: { source: true, esm: true, lines: true } });
  for (const s of schemas) ajv.addSchema(s);
  const source = standaloneCode(ajv, { [name]: schemas[0].$id });
  // Ajv reaches for its runtime helpers (string length, deep equality, URIs) with require().
  // None of the spec's schemas need one today; if one starts to, inline it here.
  if (/\brequire\(/.test(source)) throw new Error(`The ${name} validator needs one of Ajv's runtime helpers: ${source.match(/require\([^)]*\)/)![0]}`);
  if (/\bnew Function\b|\beval\(/.test(source)) throw new Error(`The ${name} validator generates code at run time`);
  const typed = source.replace(new RegExp(`export const ${name} = (validate\\d+);`), `export const ${name}: SchemaValidator = $1;`);
  if (typed === source) throw new Error(`Couldn't find the ${name} export in Ajv's output`);
  return [
    `// Generated by scripts/build-validators.ts from ${from} with Ajv's standalone output. Do not edit.`,
    "// @ts-nocheck",
    'import type { SchemaValidator } from "./schema-validator.ts";',
    typed.replace(/^"use strict";\n?/, "").trimEnd(),
    "",
  ].join("\n");
}

/** The generated validator modules, by path, for the given UI document schema. */
export async function validatorOutputs(uiSchema: Record<string, any>): Promise<Record<string, string>> {
  const [pattern, check] = await Promise.all([read("schema/pattern.schema.json"), read("schema/check.schema.json")]);
  return {
    "src/ui-validator.generated.ts": validatorModule("validateUi", [uiSchema], "schema/ui.schema.json"),
    "src/pattern-validator.generated.ts": validatorModule("validatePattern", [pattern, check], "schema/pattern.schema.json and schema/check.schema.json"),
  };
}
