/**
 * The spec's pattern checks, written as a module so the document checks (`@polyxd/verifier/static`)
 * read no files at run time and run in browsers and Workers as well as Node. A test fails when
 * this file is out of date. Run with `npm run build:patterns -w @polyxd/verifier`.
 */
import { readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const SPEC = new URL("../../spec/", import.meta.url);
const OUT = new URL("../src/patterns.generated.ts", import.meta.url);

/** The generated module's source text. */
export async function patternsSource(): Promise<string> {
  const files = (await readdir(new URL("patterns/", SPEC))).filter((f) => f.endsWith(".json")).sort();
  const patterns: Record<string, unknown> = {};
  for (const f of files) {
    const p = JSON.parse(await readFile(new URL(`patterns/${f}`, SPEC), "utf8"));
    patterns[p.id] = p.checks ?? [];
  }
  const { SPEC_VERSION } = (await import(new URL("src/version.ts", SPEC).href)) as { SPEC_VERSION: string };
  return `// Generated by scripts/build-patterns.ts from the spec (${SPEC_VERSION}). Do not edit.
import type { Rule } from "@polyxd/spec/patterns";

/** Each spec pattern's checks, by pattern id. */
export const PATTERN_CHECKS: Record<string, Rule[]> = ${JSON.stringify(patterns, null, 1)};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const source = await patternsSource();
  await writeFile(OUT, source);
  console.log(`wrote src/patterns.generated.ts (${source.length} chars)`);
}
