/** Collects each model run summary (model/runs/NAME/summary.json) into bench/results/leaderboard.md. */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";

const runs = new URL("../../../model/runs/", import.meta.url);
const out = new URL("../../../bench/results/", import.meta.url);
const rows = readdirSync(runs)
  .filter((d) => existsSync(new URL(`${d}/summary.json`, runs)))
  .map((d) => JSON.parse(readFileSync(new URL(`${d}/summary.json`, runs), "utf8")).summary)
  .sort((a, b) => b.meanScore - a.meanScore);
const cols = ["run", "validRate", "meanScore", "taskSuccess", "expectations", "directionCompliance", "consistency", "medianLatency_s", "medianTtft_s", "medianTps"];
const head = ["Model run", "Valid", "Mean score", "Agent tasks", "Expected parts", "Direction rules", "Consistency (memory / none)", "Median latency (s)", "Median TTFT (s)", "Tokens/s"];
const cell = (r: any, c: string) =>
  c === "consistency" ? `${r.consistency?.sequences ?? "—"} / ${r.consistency?.["sequences-nomem"] ?? "—"}` : String(r[c] ?? "—");
const md = [
  "# Phase 4 baselines",
  "",
  "Generated by `packages/verifier/scripts/leaderboard.ts` from each `model/runs/<run>/summary.json`. Benchmark: 50 requests in `bench/requests.json` (37 with agent tasks), scored on Material 3 light at 390 px and 1100 px. Hardware: Apple M5 Pro, 24 GB.",
  "",
  `| ${head.join(" | ")} |`,
  `|${head.map(() => "---").join("|")}|`,
  ...rows.map((r) => `| ${cols.map((c) => cell(r, c)).join(" | ")} |`),
  "",
].join("\n");
mkdirSync(out, { recursive: true });
writeFileSync(new URL("leaderboard.md", out), md);
console.log(md);
