/**
 * Precompiles the UI document schema's validator for the Worker. Ajv compiles a schema into a
 * function with `new Function`, which Cloudflare Workers forbid, so the spec's validator (and with
 * it `@polyxd/runtime`'s checks) can't compile there. This writes the same validator ahead of
 * time, with the options the spec's validate.ts uses, as worker/ui-validate.generated.js; the Worker
 * bundle aliases "ajv/dist/2020.js" to worker/ajv-2020.ts, which hands it back. Run by the build.
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { Ajv2020 } from "ajv/dist/2020.js";
import standaloneCode from "ajv/dist/standalone/index.js";
import { uiSchema } from "@polyxd/spec/browser";

const out = fileURLToPath(new URL("../worker/ui-validate.generated.js", import.meta.url));
// The same options as packages/spec/src/validate.ts, so the answers are the same.
const ajv = new Ajv2020({ allErrors: true, discriminator: true, strict: false, code: { source: true, esm: true } });
const validate = ajv.compile(uiSchema);
const code = (standaloneCode as unknown as { default?: typeof standaloneCode }).default ?? standaloneCode;
const source = code(ajv, validate);
if (/\brequire\(/.test(source)) throw new Error("The precompiled validator needs Ajv's runtime helpers; bundle them before using it in the Worker.");
await writeFile(out, `// Generated by apps/site/scripts/build-validator.ts from the spec's UI schema. Do not edit.\nexport const schemaId = ${JSON.stringify(uiSchema.$id)};\n${source}\n`);
console.log(`precompiled the UI schema validator (${Math.round(source.length / 1024)} KB) → worker/ui-validate.generated.js`);
