// Generated by scripts/sync.ts from packages/ds-*/manifest.json. Do not edit.
export interface Pack {
  /** The pack's name: the theme the renderer applies. */
  name: string;
  displayName: string;
  /** An original design to start from, rather than a published design system. */
  template: boolean;
  /** The npm package with the pack's tokens. */
  package: string;
  description: string;
}

export const PACKS: Pack[] = [
  {
    "name": "material3",
    "displayName": "Material 3",
    "template": false,
    "package": "@polyxd/ds-material3",
    "description": "Material 3 design-system pack"
  },
  {
    "name": "antd",
    "displayName": "Ant Design",
    "template": false,
    "package": "@polyxd/ds-antd",
    "description": "Ant Design design-system pack"
  },
  {
    "name": "bootstrap",
    "displayName": "Bootstrap 5",
    "template": false,
    "package": "@polyxd/ds-bootstrap",
    "description": "Bootstrap 5 design-system pack"
  },
  {
    "name": "carbon",
    "displayName": "IBM Carbon",
    "template": false,
    "package": "@polyxd/ds-carbon",
    "description": "IBM Carbon design-system pack"
  },
  {
    "name": "chakra",
    "displayName": "Chakra UI 3",
    "template": false,
    "package": "@polyxd/ds-chakra",
    "description": "Chakra UI 3 design-system pack"
  },
  {
    "name": "fluent",
    "displayName": "Microsoft Fluent 2",
    "template": false,
    "package": "@polyxd/ds-fluent",
    "description": "Microsoft Fluent 2 design-system pack"
  },
  {
    "name": "govuk",
    "displayName": "GOV.UK Frontend",
    "template": false,
    "package": "@polyxd/ds-govuk",
    "description": "GOV.UK Frontend design-system pack"
  },
  {
    "name": "mantine",
    "displayName": "Mantine 8",
    "template": false,
    "package": "@polyxd/ds-mantine",
    "description": "Mantine 8 design-system pack"
  },
  {
    "name": "polaris",
    "displayName": "Shopify Polaris",
    "template": false,
    "package": "@polyxd/ds-polaris",
    "description": "Shopify Polaris design-system pack"
  },
  {
    "name": "primer",
    "displayName": "GitHub Primer",
    "template": false,
    "package": "@polyxd/ds-primer",
    "description": "GitHub Primer design-system pack"
  },
  {
    "name": "radix",
    "displayName": "Radix Themes 3",
    "template": false,
    "package": "@polyxd/ds-radix",
    "description": "Radix Themes 3 design-system pack"
  },
  {
    "name": "shadcn",
    "displayName": "shadcn/ui on Tailwind CSS",
    "template": false,
    "package": "@polyxd/ds-shadcn",
    "description": "shadcn/ui on Tailwind CSS design-system pack"
  },
  {
    "name": "spectrum",
    "displayName": "Adobe Spectrum 2",
    "template": false,
    "package": "@polyxd/ds-spectrum",
    "description": "Adobe Spectrum 2 design-system pack"
  },
  {
    "name": "brutalist",
    "displayName": "Brutalist",
    "template": true,
    "package": "@polyxd/ds-brutalist",
    "description": "Brutalist template pack: an original design to start from and make your own"
  },
  {
    "name": "civic",
    "displayName": "Civic",
    "template": true,
    "package": "@polyxd/ds-civic",
    "description": "Civic template pack: an original design to start from and make your own"
  },
  {
    "name": "editorial",
    "displayName": "Editorial",
    "template": true,
    "package": "@polyxd/ds-editorial",
    "description": "Editorial template pack: an original design to start from and make your own"
  },
  {
    "name": "finance",
    "displayName": "Finance",
    "template": true,
    "package": "@polyxd/ds-finance",
    "description": "Finance template pack: an original design to start from and make your own"
  },
  {
    "name": "glass",
    "displayName": "Glass",
    "template": true,
    "package": "@polyxd/ds-glass",
    "description": "Glass template pack: an original design to start from and make your own"
  },
  {
    "name": "health",
    "displayName": "Health",
    "template": true,
    "package": "@polyxd/ds-health",
    "description": "Health template pack: an original design to start from and make your own"
  },
  {
    "name": "mono",
    "displayName": "Mono",
    "template": true,
    "package": "@polyxd/ds-mono",
    "description": "Mono template pack: an original design to start from and make your own"
  },
  {
    "name": "neon",
    "displayName": "Neon",
    "template": true,
    "package": "@polyxd/ds-neon",
    "description": "Neon template pack: an original design to start from and make your own"
  },
  {
    "name": "pastel",
    "displayName": "Pastel",
    "template": true,
    "package": "@polyxd/ds-pastel",
    "description": "Pastel template pack: an original design to start from and make your own"
  },
  {
    "name": "sketch",
    "displayName": "Sketch",
    "template": true,
    "package": "@polyxd/ds-sketch",
    "description": "Sketch template pack: an original design to start from and make your own"
  },
  {
    "name": "terminal",
    "displayName": "Terminal",
    "template": true,
    "package": "@polyxd/ds-terminal",
    "description": "Terminal template pack: an original design to start from and make your own"
  },
  {
    "name": "wireframe",
    "displayName": "Wireframe",
    "template": true,
    "package": "@polyxd/ds-wireframe",
    "description": "Wireframe template pack: an original design to start from and make your own"
  }
];
