// Generated by scripts/sync.ts from @polyxd/spec's components/ and examples/. Do not edit.
// Imported as JSON modules rather than read from disk, so the server runs where there is no file system.
import c0 from "@polyxd/spec/components/Action.json" with { type: "json" };
import c1 from "@polyxd/spec/components/ActionBar.json" with { type: "json" };
import c2 from "@polyxd/spec/components/ActionMenu.json" with { type: "json" };
import c3 from "@polyxd/spec/components/AppBar.json" with { type: "json" };
import c4 from "@polyxd/spec/components/Card.json" with { type: "json" };
import c5 from "@polyxd/spec/components/Chart.json" with { type: "json" };
import c6 from "@polyxd/spec/components/Choice.json" with { type: "json" };
import c7 from "@polyxd/spec/components/Code.json" with { type: "json" };
import c8 from "@polyxd/spec/components/CodeInput.json" with { type: "json" };
import c9 from "@polyxd/spec/components/Collection.json" with { type: "json" };
import c10 from "@polyxd/spec/components/ColorInput.json" with { type: "json" };
import c11 from "@polyxd/spec/components/Columns.json" with { type: "json" };
import c12 from "@polyxd/spec/components/Comparison.json" with { type: "json" };
import c13 from "@polyxd/spec/components/Confirm.json" with { type: "json" };
import c14 from "@polyxd/spec/components/Custom.json" with { type: "json" };
import c15 from "@polyxd/spec/components/DateInput.json" with { type: "json" };
import c16 from "@polyxd/spec/components/DetailList.json" with { type: "json" };
import c17 from "@polyxd/spec/components/Disclosure.json" with { type: "json" };
import c18 from "@polyxd/spec/components/FileInput.json" with { type: "json" };
import c19 from "@polyxd/spec/components/FilterPanel.json" with { type: "json" };
import c20 from "@polyxd/spec/components/Footer.json" with { type: "json" };
import c21 from "@polyxd/spec/components/Form.json" with { type: "json" };
import c22 from "@polyxd/spec/components/Frame.json" with { type: "json" };
import c23 from "@polyxd/spec/components/Group.json" with { type: "json" };
import c24 from "@polyxd/spec/components/Identity.json" with { type: "json" };
import c25 from "@polyxd/spec/components/Media.json" with { type: "json" };
import c26 from "@polyxd/spec/components/Metric.json" with { type: "json" };
import c27 from "@polyxd/spec/components/Navigation.json" with { type: "json" };
import c28 from "@polyxd/spec/components/Outlet.json" with { type: "json" };
import c29 from "@polyxd/spec/components/Panel.json" with { type: "json" };
import c30 from "@polyxd/spec/components/Progress.json" with { type: "json" };
import c31 from "@polyxd/spec/components/RangeInput.json" with { type: "json" };
import c32 from "@polyxd/spec/components/Rating.json" with { type: "json" };
import c33 from "@polyxd/spec/components/Section.json" with { type: "json" };
import c34 from "@polyxd/spec/components/Split.json" with { type: "json" };
import c35 from "@polyxd/spec/components/Status.json" with { type: "json" };
import c36 from "@polyxd/spec/components/Steps.json" with { type: "json" };
import c37 from "@polyxd/spec/components/Table.json" with { type: "json" };
import c38 from "@polyxd/spec/components/Tag.json" with { type: "json" };
import c39 from "@polyxd/spec/components/Text.json" with { type: "json" };
import c40 from "@polyxd/spec/components/TextInput.json" with { type: "json" };
import c41 from "@polyxd/spec/components/Toggle.json" with { type: "json" };
import c42 from "@polyxd/spec/components/Tree.json" with { type: "json" };
import c43 from "@polyxd/spec/components/Views.json" with { type: "json" };
import e0 from "@polyxd/spec/examples/calendar-find-slot.json" with { type: "json" };
import e1 from "@polyxd/spec/examples/crm-account-record.json" with { type: "json" };
import e2 from "@polyxd/spec/examples/crm-accounts-list.json" with { type: "json" };
import e3 from "@polyxd/spec/examples/crm-cancel-subscription.json" with { type: "json" };
import e4 from "@polyxd/spec/examples/error-load-failed.json" with { type: "json" };
import e5 from "@polyxd/spec/examples/files-move-to-folder.json" with { type: "json" };
import e6 from "@polyxd/spec/examples/money-balance-overview.json" with { type: "json" };
import e7 from "@polyxd/spec/examples/money-budget-settings.json" with { type: "json" };
import e8 from "@polyxd/spec/examples/money-send-confirm.json" with { type: "json" };
import e9 from "@polyxd/spec/examples/money-send-form.json" with { type: "json" };
import e10 from "@polyxd/spec/examples/personal-habits.json" with { type: "json" };
import e11 from "@polyxd/spec/examples/personal-reading-log.json" with { type: "json" };
import e12 from "@polyxd/spec/examples/settings-api-keys.json" with { type: "json" };
import e13 from "@polyxd/spec/examples/settings-delete-account.json" with { type: "json" };
import e14 from "@polyxd/spec/examples/settings-notifications.json" with { type: "json" };
import e15 from "@polyxd/spec/examples/shell-product.json" with { type: "json" };
import e16 from "@polyxd/spec/examples/shop-browse-filter.json" with { type: "json" };
import e17 from "@polyxd/spec/examples/shop-checkout.json" with { type: "json" };
import e18 from "@polyxd/spec/examples/shop-compare-plans.json" with { type: "json" };
import e19 from "@polyxd/spec/examples/shop-order-status.json" with { type: "json" };
import e20 from "@polyxd/spec/examples/storage-usage.json" with { type: "json" };
import e21 from "@polyxd/spec/examples/tasks-add.json" with { type: "json" };
import e22 from "@polyxd/spec/examples/tasks-archive.json" with { type: "json" };
import e23 from "@polyxd/spec/examples/tasks-delete-project.json" with { type: "json" };
import e24 from "@polyxd/spec/examples/tasks-list.json" with { type: "json" };
import e25 from "@polyxd/spec/examples/team-members.json" with { type: "json" };
import e26 from "@polyxd/spec/examples/travel-booking-review.json" with { type: "json" };
import e27 from "@polyxd/spec/examples/travel-flight-results.json" with { type: "json" };
import e28 from "@polyxd/spec/examples/travel-trip-overview.json" with { type: "json" };
import d0 from "@polyxd/spec/examples/directions/calm-finance.json" with { type: "json" };
import d1 from "@polyxd/spec/examples/directions/playful-personal.json" with { type: "json" };

export const COMPONENT_FILES: [file: string, json: unknown][] = [
  ["Action.json", c0],
  ["ActionBar.json", c1],
  ["ActionMenu.json", c2],
  ["AppBar.json", c3],
  ["Card.json", c4],
  ["Chart.json", c5],
  ["Choice.json", c6],
  ["Code.json", c7],
  ["CodeInput.json", c8],
  ["Collection.json", c9],
  ["ColorInput.json", c10],
  ["Columns.json", c11],
  ["Comparison.json", c12],
  ["Confirm.json", c13],
  ["Custom.json", c14],
  ["DateInput.json", c15],
  ["DetailList.json", c16],
  ["Disclosure.json", c17],
  ["FileInput.json", c18],
  ["FilterPanel.json", c19],
  ["Footer.json", c20],
  ["Form.json", c21],
  ["Frame.json", c22],
  ["Group.json", c23],
  ["Identity.json", c24],
  ["Media.json", c25],
  ["Metric.json", c26],
  ["Navigation.json", c27],
  ["Outlet.json", c28],
  ["Panel.json", c29],
  ["Progress.json", c30],
  ["RangeInput.json", c31],
  ["Rating.json", c32],
  ["Section.json", c33],
  ["Split.json", c34],
  ["Status.json", c35],
  ["Steps.json", c36],
  ["Table.json", c37],
  ["Tag.json", c38],
  ["Text.json", c39],
  ["TextInput.json", c40],
  ["Toggle.json", c41],
  ["Tree.json", c42],
  ["Views.json", c43],
];

export const EXAMPLE_FILES: [file: string, json: unknown][] = [
  ["calendar-find-slot.json", e0],
  ["crm-account-record.json", e1],
  ["crm-accounts-list.json", e2],
  ["crm-cancel-subscription.json", e3],
  ["error-load-failed.json", e4],
  ["files-move-to-folder.json", e5],
  ["money-balance-overview.json", e6],
  ["money-budget-settings.json", e7],
  ["money-send-confirm.json", e8],
  ["money-send-form.json", e9],
  ["personal-habits.json", e10],
  ["personal-reading-log.json", e11],
  ["settings-api-keys.json", e12],
  ["settings-delete-account.json", e13],
  ["settings-notifications.json", e14],
  ["shell-product.json", e15],
  ["shop-browse-filter.json", e16],
  ["shop-checkout.json", e17],
  ["shop-compare-plans.json", e18],
  ["shop-order-status.json", e19],
  ["storage-usage.json", e20],
  ["tasks-add.json", e21],
  ["tasks-archive.json", e22],
  ["tasks-delete-project.json", e23],
  ["tasks-list.json", e24],
  ["team-members.json", e25],
  ["travel-booking-review.json", e26],
  ["travel-flight-results.json", e27],
  ["travel-trip-overview.json", e28],
];

export const DIRECTION_FILES: [file: string, json: unknown][] = [
  ["calm-finance.json", d0],
  ["playful-personal.json", d1],
];
