/**
 * Builds the browser bundle for hosts without a bundler, and copies the stylesheet and themes the
 * package ships (the same files as @polyxd/react's, which is where they are authored):
 *
 *   preview/polyxd-web.js    window.PolyxdWeb = { mount, defineElements, registry, validateDocument, themes, specVersion, … }
 *   preview/polyxd-web.css   the renderer's styles and all themes
 *   styles.css, themes/       for `import "@polyxd/web/styles.css"` and `@polyxd/web/themes/<pack>.css`
 *
 * The script also honours the verifier harness's protocol: with `window.__PXD__ = { document,
 * theme, mode }` set before it loads, it renders into `#root` and records actions on
 * `window.__pxdActions` and semantic events on `window.__pxdEvents`, so the same page verifies
 * either renderer.
 *
 *   node scripts/build-preview.ts
 */
import { build } from "esbuild";
import { copyFile, mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const themes = (await readdir(here("../../react/themes"))).filter((f) => f.endsWith(".css")).map((f) => f.replace(/\.css$/, "")).sort();

await mkdir(here("../themes"), { recursive: true });
await mkdir(here("../preview"), { recursive: true });
await copyFile(here("../../react/src/styles.css"), here("../styles.css"));
for (const t of themes) await copyFile(here(`../../react/themes/${t}.css`), here(`../themes/${t}.css`));

const entry = `
import { defineElements, mount, registry, Skeleton, h, render, getPointer, setPointer } from "../src/index.ts";
import { validateDocument, SPEC_VERSION, flattenTree, isTree } from "@polyxd/spec/browser";
import "../styles.css";
${themes.map((t) => `import "../themes/${t}.css";`).join("\n")}

const themes = ${JSON.stringify(themes)};

/** A grey square carrying the reference as its title: generated UIs never contain URLs. */
const placeholderMedia = (ref) => "data:image/svg+xml;utf8," + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><rect width="10" height="10" fill="#999"/><title>' + String(ref).replace(/[<&]/g, "") + '</title></svg>');

defineElements();
const api = { mount: (el, props) => mount(el, { resolveMedia: placeholderMedia, ...props }), defineElements, registry, Skeleton, h, render, getPointer, setPointer, validateDocument, flattenTree, isTree, themes, specVersion: SPEC_VERSION, placeholderMedia };

if (typeof window !== "undefined") {
  window.PolyxdWeb = api;
  // The verifier harness's protocol, so a harness page renders with this bundle unchanged.
  const root = document.getElementById("root");
  if (window.__PXD__ && root) {
    window.__pxdActions = [];
    window.__pxdDismissed = 0;
    window.__pxdEvents = [];
    const { document: doc, theme, mode } = window.__PXD__;
    const shared = { document: doc, theme, mode, onAction: (e) => window.__pxdActions.push(e), onEvent: (e) => window.__pxdEvents.push(e), resolveMedia: placeholderMedia };
    if (doc.surface.kind === "shell") {
      // A shell renders with a stand-in screen in its outlet: the frame is what is being checked.
      const screen = document.createElement("div");
      screen.innerHTML = '<h1 class="pxd-surface-title">Screen</h1><p>The current screen renders here.</p>';
      mount(root, { ...shared, outlet: screen, current: { key: doc.components.find((c) => c.component === "Navigation")?.items?.[0]?.key, title: "Screen" } });
    } else {
      mount(root, { ...shared, onDismiss: () => (window.__pxdDismissed += 1) });
    }
    requestAnimationFrame(() => requestAnimationFrame(() => (window.__pxdReady = true)));
  }
}
export default api;
`;

const result = await build({
  stdin: { contents: entry, resolveDir: here("."), loader: "ts", sourcefile: "preview-entry.ts" },
  bundle: true,
  // The sources rather than the dists, so this build never waits on a stale `tsc -b` elsewhere.
  alias: { "@polyxd/spec/browser": here("../../spec/src/browser.ts"), "@polyxd/core": here("../../core/src/index.ts") },
  format: "iife",
  globalName: "PolyxdWebPreview",
  platform: "browser",
  target: ["es2022"],
  minify: true,
  legalComments: "none",
  outfile: here("../preview/polyxd-web.js"),
  logLevel: "warning",
});

const size = async (p: string) => `${Math.round((await stat(p)).size / 1024)} KB`;
const css = await readFile(here("../preview/polyxd-web.css"), "utf8");
// esbuild's CSS output keeps each theme's leading comment; one header is enough.
await writeFile(here("../preview/polyxd-web.css"), `/* @polyxd/web preview: renderer styles and the ${themes.join(", ")} themes. Generated by scripts/build-preview.ts. */\n` + css.replace(/\/\*[^*]*\*\/\s*/g, ""));
console.log(`wrote preview/polyxd-web.js (${await size(here("../preview/polyxd-web.js"))}) and preview/polyxd-web.css (${await size(here("../preview/polyxd-web.css"))}) with ${themes.length} themes`);
if (result.warnings.length) console.log(`${result.warnings.length} warning(s)`);
